{{- if .Values.config.database.url -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keyforge.fullname" . }}-db
  labels: {{- include "keyforge.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.config.database.url | quote }}
{{- end }}
