{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "keyforge.fullname" . }}
  {{- with .Values.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels: {{- include "keyforge.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels: {{- include "keyforge.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: admin
      path: /metrics
      interval: {{ .Values.serviceMonitor.interval }}
{{- end }}
