// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_log (
    tenant_id, actor_user_id, actor_client_id,
    action, target_type, target_id,
    ip, user_agent, request_id, attributes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, tenant_id, actor_user_id, actor_client_id, action, target_type, target_id, ip, user_agent, request_id, attributes, occurred_at
`

type InsertAuditEventParams struct {
	TenantID      uuid.UUID       `db:"tenant_id"`
	ActorUserID   pgtype.UUID     `db:"actor_user_id"`
	ActorClientID pgtype.UUID     `db:"actor_client_id"`
	Action        string          `db:"action"`
	TargetType    string          `db:"target_type"`
	TargetID      pgtype.Text     `db:"target_id"`
	Ip            pgtype.Text     `db:"ip"`
	UserAgent     pgtype.Text     `db:"user_agent"`
	RequestID     pgtype.Text     `db:"request_id"`
	Attributes    json.RawMessage `db:"attributes"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (*AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.TenantID,
		arg.ActorUserID,
		arg.ActorClientID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Ip,
		arg.UserAgent,
		arg.RequestID,
		arg.Attributes,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ActorUserID,
		&i.ActorClientID,
		&i.Action,
		&i.TargetType,
		&i.TargetID,
		&i.Ip,
		&i.UserAgent,
		&i.RequestID,
		&i.Attributes,
		&i.OccurredAt,
	)
	return &i, err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, tenant_id, actor_user_id, actor_client_id, action, target_type, target_id, ip, user_agent, request_id, attributes, occurred_at FROM audit_log
WHERE tenant_id = $1
  AND ($4::TEXT IS NULL OR action = $4)
  AND ($5::UUID IS NULL OR actor_user_id = $5)
  AND occurred_at < $2
ORDER BY occurred_at DESC
LIMIT $3
`

type ListAuditEventsParams struct {
	TenantID   uuid.UUID   `db:"tenant_id"`
	OccurredAt time.Time   `db:"occurred_at"`
	Limit      int32       `db:"limit"`
	Action     pgtype.Text `db:"action"`
	Actor      pgtype.UUID `db:"actor"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]*AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditEvents,
		arg.TenantID,
		arg.OccurredAt,
		arg.Limit,
		arg.Action,
		arg.Actor,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ActorUserID,
			&i.ActorClientID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Ip,
			&i.UserAgent,
			&i.RequestID,
			&i.Attributes,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
