// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth_requests.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const attachAuthRequestSession = `-- name: AttachAuthRequestSession :exec
UPDATE auth_requests
SET login_session_id = $3,
    user_id          = $4
WHERE id = $1
  AND tenant_id = $2
`

type AttachAuthRequestSessionParams struct {
	ID             uuid.UUID   `db:"id"`
	TenantID       uuid.UUID   `db:"tenant_id"`
	LoginSessionID pgtype.UUID `db:"login_session_id"`
	UserID         pgtype.UUID `db:"user_id"`
}

func (q *Queries) AttachAuthRequestSession(ctx context.Context, arg AttachAuthRequestSessionParams) error {
	_, err := q.db.Exec(ctx, attachAuthRequestSession,
		arg.ID,
		arg.TenantID,
		arg.LoginSessionID,
		arg.UserID,
	)
	return err
}

const createAuthRequest = `-- name: CreateAuthRequest :one
INSERT INTO auth_requests (
    tenant_id, client_id, redirect_uri, response_type, response_mode,
    scopes, state, nonce, code_challenge, code_challenge_method,
    prompt, max_age, ui_locales, acr_values, login_hint,
    par_request_uri, request_object_jti, expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18
)
RETURNING id, tenant_id, client_id, redirect_uri, response_type, response_mode, scopes, state, nonce, code_challenge, code_challenge_method, prompt, max_age, ui_locales, acr_values, login_hint, par_request_uri, request_object_jti, login_session_id, user_id, code_hash, code_issued_at, code_consumed_at, consented_at, created_at, expires_at, federation_idp_id, federation_state, federation_nonce, federation_pkce_verifier
`

type CreateAuthRequestParams struct {
	TenantID            uuid.UUID   `db:"tenant_id"`
	ClientID            uuid.UUID   `db:"client_id"`
	RedirectUri         string      `db:"redirect_uri"`
	ResponseType        string      `db:"response_type"`
	ResponseMode        pgtype.Text `db:"response_mode"`
	Scopes              []string    `db:"scopes"`
	State               pgtype.Text `db:"state"`
	Nonce               pgtype.Text `db:"nonce"`
	CodeChallenge       pgtype.Text `db:"code_challenge"`
	CodeChallengeMethod pgtype.Text `db:"code_challenge_method"`
	Prompt              []string    `db:"prompt"`
	MaxAge              pgtype.Int4 `db:"max_age"`
	UiLocales           pgtype.Text `db:"ui_locales"`
	AcrValues           pgtype.Text `db:"acr_values"`
	LoginHint           pgtype.Text `db:"login_hint"`
	ParRequestUri       pgtype.Text `db:"par_request_uri"`
	RequestObjectJti    pgtype.Text `db:"request_object_jti"`
	ExpiresAt           time.Time   `db:"expires_at"`
}

func (q *Queries) CreateAuthRequest(ctx context.Context, arg CreateAuthRequestParams) (*AuthRequest, error) {
	row := q.db.QueryRow(ctx, createAuthRequest,
		arg.TenantID,
		arg.ClientID,
		arg.RedirectUri,
		arg.ResponseType,
		arg.ResponseMode,
		arg.Scopes,
		arg.State,
		arg.Nonce,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.Prompt,
		arg.MaxAge,
		arg.UiLocales,
		arg.AcrValues,
		arg.LoginHint,
		arg.ParRequestUri,
		arg.RequestObjectJti,
		arg.ExpiresAt,
	)
	var i AuthRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.RedirectUri,
		&i.ResponseType,
		&i.ResponseMode,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Prompt,
		&i.MaxAge,
		&i.UiLocales,
		&i.AcrValues,
		&i.LoginHint,
		&i.ParRequestUri,
		&i.RequestObjectJti,
		&i.LoginSessionID,
		&i.UserID,
		&i.CodeHash,
		&i.CodeIssuedAt,
		&i.CodeConsumedAt,
		&i.ConsentedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FederationIdpID,
		&i.FederationState,
		&i.FederationNonce,
		&i.FederationPkceVerifier,
	)
	return &i, err
}

const getAuthRequest = `-- name: GetAuthRequest :one
SELECT id, tenant_id, client_id, redirect_uri, response_type, response_mode, scopes, state, nonce, code_challenge, code_challenge_method, prompt, max_age, ui_locales, acr_values, login_hint, par_request_uri, request_object_jti, login_session_id, user_id, code_hash, code_issued_at, code_consumed_at, consented_at, created_at, expires_at, federation_idp_id, federation_state, federation_nonce, federation_pkce_verifier FROM auth_requests
WHERE id = $1
  AND tenant_id = $2
  AND expires_at > NOW()
`

type GetAuthRequestParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetAuthRequest(ctx context.Context, arg GetAuthRequestParams) (*AuthRequest, error) {
	row := q.db.QueryRow(ctx, getAuthRequest, arg.ID, arg.TenantID)
	var i AuthRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.RedirectUri,
		&i.ResponseType,
		&i.ResponseMode,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Prompt,
		&i.MaxAge,
		&i.UiLocales,
		&i.AcrValues,
		&i.LoginHint,
		&i.ParRequestUri,
		&i.RequestObjectJti,
		&i.LoginSessionID,
		&i.UserID,
		&i.CodeHash,
		&i.CodeIssuedAt,
		&i.CodeConsumedAt,
		&i.ConsentedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FederationIdpID,
		&i.FederationState,
		&i.FederationNonce,
		&i.FederationPkceVerifier,
	)
	return &i, err
}

const getAuthRequestByCodeHash = `-- name: GetAuthRequestByCodeHash :one
SELECT id, tenant_id, client_id, redirect_uri, response_type, response_mode, scopes, state, nonce, code_challenge, code_challenge_method, prompt, max_age, ui_locales, acr_values, login_hint, par_request_uri, request_object_jti, login_session_id, user_id, code_hash, code_issued_at, code_consumed_at, consented_at, created_at, expires_at, federation_idp_id, federation_state, federation_nonce, federation_pkce_verifier FROM auth_requests
WHERE code_hash = $1
  AND tenant_id = $2
`

type GetAuthRequestByCodeHashParams struct {
	CodeHash pgtype.Text `db:"code_hash"`
	TenantID uuid.UUID   `db:"tenant_id"`
}

func (q *Queries) GetAuthRequestByCodeHash(ctx context.Context, arg GetAuthRequestByCodeHashParams) (*AuthRequest, error) {
	row := q.db.QueryRow(ctx, getAuthRequestByCodeHash, arg.CodeHash, arg.TenantID)
	var i AuthRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.RedirectUri,
		&i.ResponseType,
		&i.ResponseMode,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Prompt,
		&i.MaxAge,
		&i.UiLocales,
		&i.AcrValues,
		&i.LoginHint,
		&i.ParRequestUri,
		&i.RequestObjectJti,
		&i.LoginSessionID,
		&i.UserID,
		&i.CodeHash,
		&i.CodeIssuedAt,
		&i.CodeConsumedAt,
		&i.ConsentedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FederationIdpID,
		&i.FederationState,
		&i.FederationNonce,
		&i.FederationPkceVerifier,
	)
	return &i, err
}

const markAuthRequestCodeConsumed = `-- name: MarkAuthRequestCodeConsumed :exec
UPDATE auth_requests
SET code_consumed_at = NOW()
WHERE id = $1
  AND tenant_id = $2
  AND code_consumed_at IS NULL
`

type MarkAuthRequestCodeConsumedParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) MarkAuthRequestCodeConsumed(ctx context.Context, arg MarkAuthRequestCodeConsumedParams) error {
	_, err := q.db.Exec(ctx, markAuthRequestCodeConsumed, arg.ID, arg.TenantID)
	return err
}

const markAuthRequestConsentedAndCode = `-- name: MarkAuthRequestConsentedAndCode :exec
UPDATE auth_requests
SET consented_at   = NOW(),
    code_hash      = $3,
    code_issued_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type MarkAuthRequestConsentedAndCodeParams struct {
	ID       uuid.UUID   `db:"id"`
	TenantID uuid.UUID   `db:"tenant_id"`
	CodeHash pgtype.Text `db:"code_hash"`
}

func (q *Queries) MarkAuthRequestConsentedAndCode(ctx context.Context, arg MarkAuthRequestConsentedAndCodeParams) error {
	_, err := q.db.Exec(ctx, markAuthRequestConsentedAndCode, arg.ID, arg.TenantID, arg.CodeHash)
	return err
}
