// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ciba.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getCIBAByAuthReqID = `-- name: GetCIBAByAuthReqID :one
SELECT id, tenant_id, client_id, auth_req_id, user_id, binding_message, scopes, audience, acr_values, interval_seconds, last_polled_at, status, created_at, expires_at FROM ciba_requests
WHERE auth_req_id = $1
  AND tenant_id   = $2
FOR UPDATE
`

type GetCIBAByAuthReqIDParams struct {
	AuthReqID string    `db:"auth_req_id"`
	TenantID  uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetCIBAByAuthReqID(ctx context.Context, arg GetCIBAByAuthReqIDParams) (*CibaRequest, error) {
	row := q.db.QueryRow(ctx, getCIBAByAuthReqID, arg.AuthReqID, arg.TenantID)
	var i CibaRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.AuthReqID,
		&i.UserID,
		&i.BindingMessage,
		&i.Scopes,
		&i.Audience,
		&i.AcrValues,
		&i.IntervalSeconds,
		&i.LastPolledAt,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const insertCIBARequest = `-- name: InsertCIBARequest :one
INSERT INTO ciba_requests (
    tenant_id, client_id, auth_req_id, user_id, binding_message,
    scopes, audience, acr_values, interval_seconds, expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10
)
RETURNING id, tenant_id, client_id, auth_req_id, user_id, binding_message, scopes, audience, acr_values, interval_seconds, last_polled_at, status, created_at, expires_at
`

type InsertCIBARequestParams struct {
	TenantID        uuid.UUID   `db:"tenant_id"`
	ClientID        uuid.UUID   `db:"client_id"`
	AuthReqID       string      `db:"auth_req_id"`
	UserID          pgtype.UUID `db:"user_id"`
	BindingMessage  pgtype.Text `db:"binding_message"`
	Scopes          []string    `db:"scopes"`
	Audience        []string    `db:"audience"`
	AcrValues       pgtype.Text `db:"acr_values"`
	IntervalSeconds int32       `db:"interval_seconds"`
	ExpiresAt       time.Time   `db:"expires_at"`
}

func (q *Queries) InsertCIBARequest(ctx context.Context, arg InsertCIBARequestParams) (*CibaRequest, error) {
	row := q.db.QueryRow(ctx, insertCIBARequest,
		arg.TenantID,
		arg.ClientID,
		arg.AuthReqID,
		arg.UserID,
		arg.BindingMessage,
		arg.Scopes,
		arg.Audience,
		arg.AcrValues,
		arg.IntervalSeconds,
		arg.ExpiresAt,
	)
	var i CibaRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.AuthReqID,
		&i.UserID,
		&i.BindingMessage,
		&i.Scopes,
		&i.Audience,
		&i.AcrValues,
		&i.IntervalSeconds,
		&i.LastPolledAt,
		&i.Status,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const listPendingCIBAForUser = `-- name: ListPendingCIBAForUser :many
SELECT id, tenant_id, client_id, auth_req_id, user_id, binding_message, scopes, audience, acr_values, interval_seconds, last_polled_at, status, created_at, expires_at FROM ciba_requests
WHERE tenant_id = $1
  AND user_id   = $2
  AND status    = 'pending'
  AND expires_at > NOW()
ORDER BY created_at DESC
`

type ListPendingCIBAForUserParams struct {
	TenantID uuid.UUID   `db:"tenant_id"`
	UserID   pgtype.UUID `db:"user_id"`
}

func (q *Queries) ListPendingCIBAForUser(ctx context.Context, arg ListPendingCIBAForUserParams) ([]*CibaRequest, error) {
	rows, err := q.db.Query(ctx, listPendingCIBAForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*CibaRequest{}
	for rows.Next() {
		var i CibaRequest
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.AuthReqID,
			&i.UserID,
			&i.BindingMessage,
			&i.Scopes,
			&i.Audience,
			&i.AcrValues,
			&i.IntervalSeconds,
			&i.LastPolledAt,
			&i.Status,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCIBAStatus = `-- name: SetCIBAStatus :exec
UPDATE ciba_requests
SET status = $3
WHERE id = $1
  AND tenant_id = $2
`

type SetCIBAStatusParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
	Status   string    `db:"status"`
}

func (q *Queries) SetCIBAStatus(ctx context.Context, arg SetCIBAStatusParams) error {
	_, err := q.db.Exec(ctx, setCIBAStatus, arg.ID, arg.TenantID, arg.Status)
	return err
}

const touchCIBAPoll = `-- name: TouchCIBAPoll :exec
UPDATE ciba_requests
SET last_polled_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type TouchCIBAPollParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) TouchCIBAPoll(ctx context.Context, arg TouchCIBAPollParams) error {
	_, err := q.db.Exec(ctx, touchCIBAPoll, arg.ID, arg.TenantID)
	return err
}
