// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: client_resources.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addClientAllowedResource = `-- name: AddClientAllowedResource :exec
INSERT INTO client_allowed_resources (tenant_id, client_id, resource)
VALUES ($1, $2, $3)
ON CONFLICT (client_id, resource) DO NOTHING
`

type AddClientAllowedResourceParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	ClientID uuid.UUID `db:"client_id"`
	Resource string    `db:"resource"`
}

func (q *Queries) AddClientAllowedResource(ctx context.Context, arg AddClientAllowedResourceParams) error {
	_, err := q.db.Exec(ctx, addClientAllowedResource, arg.TenantID, arg.ClientID, arg.Resource)
	return err
}

const deleteClientAllowedResource = `-- name: DeleteClientAllowedResource :exec
DELETE FROM client_allowed_resources
WHERE tenant_id = $1
  AND client_id = $2
  AND resource   = $3
`

type DeleteClientAllowedResourceParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	ClientID uuid.UUID `db:"client_id"`
	Resource string    `db:"resource"`
}

func (q *Queries) DeleteClientAllowedResource(ctx context.Context, arg DeleteClientAllowedResourceParams) error {
	_, err := q.db.Exec(ctx, deleteClientAllowedResource, arg.TenantID, arg.ClientID, arg.Resource)
	return err
}

const listClientAllowedResources = `-- name: ListClientAllowedResources :many
SELECT resource FROM client_allowed_resources
WHERE tenant_id = $1
  AND client_id = $2
ORDER BY resource
`

type ListClientAllowedResourcesParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	ClientID uuid.UUID `db:"client_id"`
}

func (q *Queries) ListClientAllowedResources(ctx context.Context, arg ListClientAllowedResourcesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listClientAllowedResources, arg.TenantID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var resource string
		if err := rows.Scan(&resource); err != nil {
			return nil, err
		}
		items = append(items, resource)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceClientAllowedResources = `-- name: ReplaceClientAllowedResources :exec
DELETE FROM client_allowed_resources
WHERE tenant_id = $1
  AND client_id = $2
`

type ReplaceClientAllowedResourcesParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	ClientID uuid.UUID `db:"client_id"`
}

func (q *Queries) ReplaceClientAllowedResources(ctx context.Context, arg ReplaceClientAllowedResourcesParams) error {
	_, err := q.db.Exec(ctx, replaceClientAllowedResources, arg.TenantID, arg.ClientID)
	return err
}
