// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: clients.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addClientRedirectURI = `-- name: AddClientRedirectURI :exec
INSERT INTO client_redirect_uris (tenant_id, client_id, redirect_uri)
VALUES ($1, $2, $3)
ON CONFLICT (client_id, redirect_uri) DO NOTHING
`

type AddClientRedirectURIParams struct {
	TenantID    uuid.UUID `db:"tenant_id"`
	ClientID    uuid.UUID `db:"client_id"`
	RedirectUri string    `db:"redirect_uri"`
}

func (q *Queries) AddClientRedirectURI(ctx context.Context, arg AddClientRedirectURIParams) error {
	_, err := q.db.Exec(ctx, addClientRedirectURI, arg.TenantID, arg.ClientID, arg.RedirectUri)
	return err
}

const createClient = `-- name: CreateClient :one
INSERT INTO clients (
    tenant_id, client_id, client_secret_hash, client_type, name, description,
    grant_types, response_types, response_modes, scopes,
    token_endpoint_auth_method, token_endpoint_auth_signing_alg,
    request_object_signing_alg, require_signed_request_object,
    require_par, require_dpop, dpop_bound_access_tokens,
    tls_client_auth_subject_dn, tls_client_certificate_bound_access_tokens,
    authorization_signed_response_alg,
    jwks_uri, jwks,
    backchannel_token_delivery_mode, backchannel_client_notification_endpoint,
    is_federation_client
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10,
    $11, $12,
    $13, $14,
    $15, $16, $17,
    $18, $19,
    $20,
    $21, $22,
    $23, $24,
    $25
)
RETURNING id, tenant_id, client_id, client_secret_hash, client_type, name, description, grant_types, response_types, response_modes, scopes, token_endpoint_auth_method, token_endpoint_auth_signing_alg, request_object_signing_alg, require_signed_request_object, require_par, require_dpop, dpop_bound_access_tokens, tls_client_auth_subject_dn, tls_client_certificate_bound_access_tokens, authorization_signed_response_alg, jwks_uri, jwks, backchannel_token_delivery_mode, backchannel_client_notification_endpoint, is_federation_client, enabled, created_at, updated_at
`

type CreateClientParams struct {
	TenantID                              uuid.UUID   `db:"tenant_id"`
	ClientID                              string      `db:"client_id"`
	ClientSecretHash                      pgtype.Text `db:"client_secret_hash"`
	ClientType                            string      `db:"client_type"`
	Name                                  string      `db:"name"`
	Description                           pgtype.Text `db:"description"`
	GrantTypes                            []string    `db:"grant_types"`
	ResponseTypes                         []string    `db:"response_types"`
	ResponseModes                         []string    `db:"response_modes"`
	Scopes                                []string    `db:"scopes"`
	TokenEndpointAuthMethod               string      `db:"token_endpoint_auth_method"`
	TokenEndpointAuthSigningAlg           pgtype.Text `db:"token_endpoint_auth_signing_alg"`
	RequestObjectSigningAlg               pgtype.Text `db:"request_object_signing_alg"`
	RequireSignedRequestObject            bool        `db:"require_signed_request_object"`
	RequirePAR                            bool        `db:"require_par"`
	RequireDPoP                           bool        `db:"require_dpop"`
	DPoPBoundAccessTokens                 bool        `db:"dpop_bound_access_tokens"`
	TLSClientAuthSubjectDN                pgtype.Text `db:"tls_client_auth_subject_dn"`
	TLSClientCertificateBoundAccessTokens bool        `db:"tls_client_certificate_bound_access_tokens"`
	AuthorizationSignedResponseAlg        pgtype.Text `db:"authorization_signed_response_alg"`
	JWKSURI                               pgtype.Text `db:"jwks_uri"`
	Jwks                                  []byte      `db:"jwks"`
	BackchannelTokenDeliveryMode          pgtype.Text `db:"backchannel_token_delivery_mode"`
	BackchannelClientNotificationEndpoint pgtype.Text `db:"backchannel_client_notification_endpoint"`
	IsFederationClient                    bool        `db:"is_federation_client"`
}

func (q *Queries) CreateClient(ctx context.Context, arg CreateClientParams) (*Client, error) {
	row := q.db.QueryRow(ctx, createClient,
		arg.TenantID,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.ClientType,
		arg.Name,
		arg.Description,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.ResponseModes,
		arg.Scopes,
		arg.TokenEndpointAuthMethod,
		arg.TokenEndpointAuthSigningAlg,
		arg.RequestObjectSigningAlg,
		arg.RequireSignedRequestObject,
		arg.RequirePAR,
		arg.RequireDPoP,
		arg.DPoPBoundAccessTokens,
		arg.TLSClientAuthSubjectDN,
		arg.TLSClientCertificateBoundAccessTokens,
		arg.AuthorizationSignedResponseAlg,
		arg.JWKSURI,
		arg.Jwks,
		arg.BackchannelTokenDeliveryMode,
		arg.BackchannelClientNotificationEndpoint,
		arg.IsFederationClient,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientType,
		&i.Name,
		&i.Description,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ResponseModes,
		&i.Scopes,
		&i.TokenEndpointAuthMethod,
		&i.TokenEndpointAuthSigningAlg,
		&i.RequestObjectSigningAlg,
		&i.RequireSignedRequestObject,
		&i.RequirePAR,
		&i.RequireDPoP,
		&i.DPoPBoundAccessTokens,
		&i.TLSClientAuthSubjectDN,
		&i.TLSClientCertificateBoundAccessTokens,
		&i.AuthorizationSignedResponseAlg,
		&i.JWKSURI,
		&i.Jwks,
		&i.BackchannelTokenDeliveryMode,
		&i.BackchannelClientNotificationEndpoint,
		&i.IsFederationClient,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteClient = `-- name: DeleteClient :exec
DELETE FROM clients
WHERE id = $1
  AND tenant_id = $2
`

type DeleteClientParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) DeleteClient(ctx context.Context, arg DeleteClientParams) error {
	_, err := q.db.Exec(ctx, deleteClient, arg.ID, arg.TenantID)
	return err
}

const deleteClientRedirectURI = `-- name: DeleteClientRedirectURI :exec
DELETE FROM client_redirect_uris
WHERE tenant_id = $1
  AND client_id = $2
  AND redirect_uri = $3
`

type DeleteClientRedirectURIParams struct {
	TenantID    uuid.UUID `db:"tenant_id"`
	ClientID    uuid.UUID `db:"client_id"`
	RedirectUri string    `db:"redirect_uri"`
}

func (q *Queries) DeleteClientRedirectURI(ctx context.Context, arg DeleteClientRedirectURIParams) error {
	_, err := q.db.Exec(ctx, deleteClientRedirectURI, arg.TenantID, arg.ClientID, arg.RedirectUri)
	return err
}

const getClientByClientID = `-- name: GetClientByClientID :one
SELECT id, tenant_id, client_id, client_secret_hash, client_type, name, description, grant_types, response_types, response_modes, scopes, token_endpoint_auth_method, token_endpoint_auth_signing_alg, request_object_signing_alg, require_signed_request_object, require_par, require_dpop, dpop_bound_access_tokens, tls_client_auth_subject_dn, tls_client_certificate_bound_access_tokens, authorization_signed_response_alg, jwks_uri, jwks, backchannel_token_delivery_mode, backchannel_client_notification_endpoint, is_federation_client, enabled, created_at, updated_at FROM clients
WHERE tenant_id = $1
  AND client_id = $2
`

type GetClientByClientIDParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	ClientID string    `db:"client_id"`
}

func (q *Queries) GetClientByClientID(ctx context.Context, arg GetClientByClientIDParams) (*Client, error) {
	row := q.db.QueryRow(ctx, getClientByClientID, arg.TenantID, arg.ClientID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientType,
		&i.Name,
		&i.Description,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ResponseModes,
		&i.Scopes,
		&i.TokenEndpointAuthMethod,
		&i.TokenEndpointAuthSigningAlg,
		&i.RequestObjectSigningAlg,
		&i.RequireSignedRequestObject,
		&i.RequirePAR,
		&i.RequireDPoP,
		&i.DPoPBoundAccessTokens,
		&i.TLSClientAuthSubjectDN,
		&i.TLSClientCertificateBoundAccessTokens,
		&i.AuthorizationSignedResponseAlg,
		&i.JWKSURI,
		&i.Jwks,
		&i.BackchannelTokenDeliveryMode,
		&i.BackchannelClientNotificationEndpoint,
		&i.IsFederationClient,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getClientByID = `-- name: GetClientByID :one
SELECT id, tenant_id, client_id, client_secret_hash, client_type, name, description, grant_types, response_types, response_modes, scopes, token_endpoint_auth_method, token_endpoint_auth_signing_alg, request_object_signing_alg, require_signed_request_object, require_par, require_dpop, dpop_bound_access_tokens, tls_client_auth_subject_dn, tls_client_certificate_bound_access_tokens, authorization_signed_response_alg, jwks_uri, jwks, backchannel_token_delivery_mode, backchannel_client_notification_endpoint, is_federation_client, enabled, created_at, updated_at FROM clients
WHERE id = $1
  AND tenant_id = $2
`

type GetClientByIDParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetClientByID(ctx context.Context, arg GetClientByIDParams) (*Client, error) {
	row := q.db.QueryRow(ctx, getClientByID, arg.ID, arg.TenantID)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientType,
		&i.Name,
		&i.Description,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ResponseModes,
		&i.Scopes,
		&i.TokenEndpointAuthMethod,
		&i.TokenEndpointAuthSigningAlg,
		&i.RequestObjectSigningAlg,
		&i.RequireSignedRequestObject,
		&i.RequirePAR,
		&i.RequireDPoP,
		&i.DPoPBoundAccessTokens,
		&i.TLSClientAuthSubjectDN,
		&i.TLSClientCertificateBoundAccessTokens,
		&i.AuthorizationSignedResponseAlg,
		&i.JWKSURI,
		&i.Jwks,
		&i.BackchannelTokenDeliveryMode,
		&i.BackchannelClientNotificationEndpoint,
		&i.IsFederationClient,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listClientRedirectURIs = `-- name: ListClientRedirectURIs :many
SELECT redirect_uri FROM client_redirect_uris
WHERE tenant_id = $1
  AND client_id = $2
ORDER BY redirect_uri
`

type ListClientRedirectURIsParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	ClientID uuid.UUID `db:"client_id"`
}

func (q *Queries) ListClientRedirectURIs(ctx context.Context, arg ListClientRedirectURIsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listClientRedirectURIs, arg.TenantID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var redirect_uri string
		if err := rows.Scan(&redirect_uri); err != nil {
			return nil, err
		}
		items = append(items, redirect_uri)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClientsByTenant = `-- name: ListClientsByTenant :many
SELECT id, tenant_id, client_id, client_secret_hash, client_type, name, description, grant_types, response_types, response_modes, scopes, token_endpoint_auth_method, token_endpoint_auth_signing_alg, request_object_signing_alg, require_signed_request_object, require_par, require_dpop, dpop_bound_access_tokens, tls_client_auth_subject_dn, tls_client_certificate_bound_access_tokens, authorization_signed_response_alg, jwks_uri, jwks, backchannel_token_delivery_mode, backchannel_client_notification_endpoint, is_federation_client, enabled, created_at, updated_at FROM clients
WHERE tenant_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListClientsByTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	Limit    int32     `db:"limit"`
	Offset   int32     `db:"offset"`
}

func (q *Queries) ListClientsByTenant(ctx context.Context, arg ListClientsByTenantParams) ([]*Client, error) {
	rows, err := q.db.Query(ctx, listClientsByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Client{}
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.ClientType,
			&i.Name,
			&i.Description,
			&i.GrantTypes,
			&i.ResponseTypes,
			&i.ResponseModes,
			&i.Scopes,
			&i.TokenEndpointAuthMethod,
			&i.TokenEndpointAuthSigningAlg,
			&i.RequestObjectSigningAlg,
			&i.RequireSignedRequestObject,
			&i.RequirePAR,
			&i.RequireDPoP,
			&i.DPoPBoundAccessTokens,
			&i.TLSClientAuthSubjectDN,
			&i.TLSClientCertificateBoundAccessTokens,
			&i.AuthorizationSignedResponseAlg,
			&i.JWKSURI,
			&i.Jwks,
			&i.BackchannelTokenDeliveryMode,
			&i.BackchannelClientNotificationEndpoint,
			&i.IsFederationClient,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceClientRedirectURIs = `-- name: ReplaceClientRedirectURIs :exec
DELETE FROM client_redirect_uris
WHERE tenant_id = $1
  AND client_id = $2
`

type ReplaceClientRedirectURIsParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	ClientID uuid.UUID `db:"client_id"`
}

func (q *Queries) ReplaceClientRedirectURIs(ctx context.Context, arg ReplaceClientRedirectURIsParams) error {
	_, err := q.db.Exec(ctx, replaceClientRedirectURIs, arg.TenantID, arg.ClientID)
	return err
}

const rotateClientSecret = `-- name: RotateClientSecret :exec
UPDATE clients
SET client_secret_hash = $3,
    updated_at         = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type RotateClientSecretParams struct {
	ID               uuid.UUID   `db:"id"`
	TenantID         uuid.UUID   `db:"tenant_id"`
	ClientSecretHash pgtype.Text `db:"client_secret_hash"`
}

func (q *Queries) RotateClientSecret(ctx context.Context, arg RotateClientSecretParams) error {
	_, err := q.db.Exec(ctx, rotateClientSecret, arg.ID, arg.TenantID, arg.ClientSecretHash)
	return err
}

const updateClient = `-- name: UpdateClient :one
UPDATE clients
SET name                                       = $3,
    description                                = $4,
    grant_types                                = $5,
    response_types                             = $6,
    response_modes                             = $7,
    scopes                                     = $8,
    token_endpoint_auth_method                 = $9,
    token_endpoint_auth_signing_alg            = $10,
    request_object_signing_alg                 = $11,
    require_signed_request_object              = $12,
    require_par                                = $13,
    require_dpop                               = $14,
    dpop_bound_access_tokens                   = $15,
    tls_client_auth_subject_dn                 = $16,
    tls_client_certificate_bound_access_tokens = $17,
    authorization_signed_response_alg          = $18,
    jwks_uri                                   = $19,
    jwks                                       = $20,
    backchannel_token_delivery_mode            = $21,
    backchannel_client_notification_endpoint   = $22,
    enabled                                    = $23,
    updated_at                                 = NOW()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, client_id, client_secret_hash, client_type, name, description, grant_types, response_types, response_modes, scopes, token_endpoint_auth_method, token_endpoint_auth_signing_alg, request_object_signing_alg, require_signed_request_object, require_par, require_dpop, dpop_bound_access_tokens, tls_client_auth_subject_dn, tls_client_certificate_bound_access_tokens, authorization_signed_response_alg, jwks_uri, jwks, backchannel_token_delivery_mode, backchannel_client_notification_endpoint, is_federation_client, enabled, created_at, updated_at
`

type UpdateClientParams struct {
	ID                                    uuid.UUID   `db:"id"`
	TenantID                              uuid.UUID   `db:"tenant_id"`
	Name                                  string      `db:"name"`
	Description                           pgtype.Text `db:"description"`
	GrantTypes                            []string    `db:"grant_types"`
	ResponseTypes                         []string    `db:"response_types"`
	ResponseModes                         []string    `db:"response_modes"`
	Scopes                                []string    `db:"scopes"`
	TokenEndpointAuthMethod               string      `db:"token_endpoint_auth_method"`
	TokenEndpointAuthSigningAlg           pgtype.Text `db:"token_endpoint_auth_signing_alg"`
	RequestObjectSigningAlg               pgtype.Text `db:"request_object_signing_alg"`
	RequireSignedRequestObject            bool        `db:"require_signed_request_object"`
	RequirePAR                            bool        `db:"require_par"`
	RequireDPoP                           bool        `db:"require_dpop"`
	DPoPBoundAccessTokens                 bool        `db:"dpop_bound_access_tokens"`
	TLSClientAuthSubjectDN                pgtype.Text `db:"tls_client_auth_subject_dn"`
	TLSClientCertificateBoundAccessTokens bool        `db:"tls_client_certificate_bound_access_tokens"`
	AuthorizationSignedResponseAlg        pgtype.Text `db:"authorization_signed_response_alg"`
	JWKSURI                               pgtype.Text `db:"jwks_uri"`
	Jwks                                  []byte      `db:"jwks"`
	BackchannelTokenDeliveryMode          pgtype.Text `db:"backchannel_token_delivery_mode"`
	BackchannelClientNotificationEndpoint pgtype.Text `db:"backchannel_client_notification_endpoint"`
	Enabled                               bool        `db:"enabled"`
}

func (q *Queries) UpdateClient(ctx context.Context, arg UpdateClientParams) (*Client, error) {
	row := q.db.QueryRow(ctx, updateClient,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.GrantTypes,
		arg.ResponseTypes,
		arg.ResponseModes,
		arg.Scopes,
		arg.TokenEndpointAuthMethod,
		arg.TokenEndpointAuthSigningAlg,
		arg.RequestObjectSigningAlg,
		arg.RequireSignedRequestObject,
		arg.RequirePAR,
		arg.RequireDPoP,
		arg.DPoPBoundAccessTokens,
		arg.TLSClientAuthSubjectDN,
		arg.TLSClientCertificateBoundAccessTokens,
		arg.AuthorizationSignedResponseAlg,
		arg.JWKSURI,
		arg.Jwks,
		arg.BackchannelTokenDeliveryMode,
		arg.BackchannelClientNotificationEndpoint,
		arg.Enabled,
	)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientType,
		&i.Name,
		&i.Description,
		&i.GrantTypes,
		&i.ResponseTypes,
		&i.ResponseModes,
		&i.Scopes,
		&i.TokenEndpointAuthMethod,
		&i.TokenEndpointAuthSigningAlg,
		&i.RequestObjectSigningAlg,
		&i.RequireSignedRequestObject,
		&i.RequirePAR,
		&i.RequireDPoP,
		&i.DPoPBoundAccessTokens,
		&i.TLSClientAuthSubjectDN,
		&i.TLSClientCertificateBoundAccessTokens,
		&i.AuthorizationSignedResponseAlg,
		&i.JWKSURI,
		&i.Jwks,
		&i.BackchannelTokenDeliveryMode,
		&i.BackchannelClientNotificationEndpoint,
		&i.IsFederationClient,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
