// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: consents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getActiveUserConsent = `-- name: GetActiveUserConsent :one
SELECT id, tenant_id, user_id, client_id, scopes, granted_at, revoked_at FROM user_consents
WHERE tenant_id = $1
  AND user_id   = $2
  AND client_id = $3
  AND revoked_at IS NULL
ORDER BY granted_at DESC
LIMIT 1
`

type GetActiveUserConsentParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
	ClientID uuid.UUID `db:"client_id"`
}

func (q *Queries) GetActiveUserConsent(ctx context.Context, arg GetActiveUserConsentParams) (*UserConsent, error) {
	row := q.db.QueryRow(ctx, getActiveUserConsent, arg.TenantID, arg.UserID, arg.ClientID)
	var i UserConsent
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.ClientID,
		&i.Scopes,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const listUserConsents = `-- name: ListUserConsents :many
SELECT id, tenant_id, user_id, client_id, scopes, granted_at, revoked_at FROM user_consents
WHERE tenant_id = $1
  AND user_id   = $2
  AND revoked_at IS NULL
ORDER BY granted_at DESC
`

type ListUserConsentsParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

func (q *Queries) ListUserConsents(ctx context.Context, arg ListUserConsentsParams) ([]*UserConsent, error) {
	rows, err := q.db.Query(ctx, listUserConsents, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserConsent{}
	for rows.Next() {
		var i UserConsent
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.ClientID,
			&i.Scopes,
			&i.GrantedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeUserConsent = `-- name: RevokeUserConsent :exec
UPDATE user_consents
SET revoked_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type RevokeUserConsentParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) RevokeUserConsent(ctx context.Context, arg RevokeUserConsentParams) error {
	_, err := q.db.Exec(ctx, revokeUserConsent, arg.ID, arg.TenantID)
	return err
}

const upsertUserConsent = `-- name: UpsertUserConsent :exec
INSERT INTO user_consents (tenant_id, user_id, client_id, scopes)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, user_id, client_id) WHERE revoked_at IS NULL
DO UPDATE SET
    scopes     = EXCLUDED.scopes,
    granted_at = NOW()
`

type UpsertUserConsentParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
	ClientID uuid.UUID `db:"client_id"`
	Scopes   []string  `db:"scopes"`
}

func (q *Queries) UpsertUserConsent(ctx context.Context, arg UpsertUserConsentParams) error {
	_, err := q.db.Exec(ctx, upsertUserConsent,
		arg.TenantID,
		arg.UserID,
		arg.ClientID,
		arg.Scopes,
	)
	return err
}
