// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveDeviceCode = `-- name: ApproveDeviceCode :exec
UPDATE device_codes
SET approved = TRUE,
    user_id  = $3
WHERE id = $1
  AND tenant_id = $2
  AND approved = FALSE
  AND denied   = FALSE
`

type ApproveDeviceCodeParams struct {
	ID       uuid.UUID   `db:"id"`
	TenantID uuid.UUID   `db:"tenant_id"`
	UserID   pgtype.UUID `db:"user_id"`
}

func (q *Queries) ApproveDeviceCode(ctx context.Context, arg ApproveDeviceCodeParams) error {
	_, err := q.db.Exec(ctx, approveDeviceCode, arg.ID, arg.TenantID, arg.UserID)
	return err
}

const denyDeviceCode = `-- name: DenyDeviceCode :exec
UPDATE device_codes
SET denied = TRUE
WHERE id = $1
  AND tenant_id = $2
  AND approved = FALSE
  AND denied   = FALSE
`

type DenyDeviceCodeParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) DenyDeviceCode(ctx context.Context, arg DenyDeviceCodeParams) error {
	_, err := q.db.Exec(ctx, denyDeviceCode, arg.ID, arg.TenantID)
	return err
}

const getDeviceCodeByDeviceCode = `-- name: GetDeviceCodeByDeviceCode :one
SELECT id, tenant_id, client_id, device_code, user_code, scopes, audience, interval_seconds, last_polled_at, user_id, approved, denied, redeemed_at, created_at, expires_at FROM device_codes
WHERE device_code = $1
  AND tenant_id   = $2
FOR UPDATE
`

type GetDeviceCodeByDeviceCodeParams struct {
	DeviceCode string    `db:"device_code"`
	TenantID   uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetDeviceCodeByDeviceCode(ctx context.Context, arg GetDeviceCodeByDeviceCodeParams) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeByDeviceCode, arg.DeviceCode, arg.TenantID)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.DeviceCode,
		&i.UserCode,
		&i.Scopes,
		&i.Audience,
		&i.IntervalSeconds,
		&i.LastPolledAt,
		&i.UserID,
		&i.Approved,
		&i.Denied,
		&i.RedeemedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const getDeviceCodeByUserCode = `-- name: GetDeviceCodeByUserCode :one
SELECT id, tenant_id, client_id, device_code, user_code, scopes, audience, interval_seconds, last_polled_at, user_id, approved, denied, redeemed_at, created_at, expires_at FROM device_codes
WHERE user_code = $1
  AND tenant_id = $2
FOR UPDATE
`

type GetDeviceCodeByUserCodeParams struct {
	UserCode string    `db:"user_code"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetDeviceCodeByUserCode(ctx context.Context, arg GetDeviceCodeByUserCodeParams) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, getDeviceCodeByUserCode, arg.UserCode, arg.TenantID)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.DeviceCode,
		&i.UserCode,
		&i.Scopes,
		&i.Audience,
		&i.IntervalSeconds,
		&i.LastPolledAt,
		&i.UserID,
		&i.Approved,
		&i.Denied,
		&i.RedeemedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const insertDeviceCode = `-- name: InsertDeviceCode :one
INSERT INTO device_codes (
    tenant_id, client_id, device_code, user_code, scopes, audience,
    interval_seconds, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, tenant_id, client_id, device_code, user_code, scopes, audience, interval_seconds, last_polled_at, user_id, approved, denied, redeemed_at, created_at, expires_at
`

type InsertDeviceCodeParams struct {
	TenantID        uuid.UUID `db:"tenant_id"`
	ClientID        uuid.UUID `db:"client_id"`
	DeviceCode      string    `db:"device_code"`
	UserCode        string    `db:"user_code"`
	Scopes          []string  `db:"scopes"`
	Audience        []string  `db:"audience"`
	IntervalSeconds int32     `db:"interval_seconds"`
	ExpiresAt       time.Time `db:"expires_at"`
}

func (q *Queries) InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) (*DeviceCode, error) {
	row := q.db.QueryRow(ctx, insertDeviceCode,
		arg.TenantID,
		arg.ClientID,
		arg.DeviceCode,
		arg.UserCode,
		arg.Scopes,
		arg.Audience,
		arg.IntervalSeconds,
		arg.ExpiresAt,
	)
	var i DeviceCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.DeviceCode,
		&i.UserCode,
		&i.Scopes,
		&i.Audience,
		&i.IntervalSeconds,
		&i.LastPolledAt,
		&i.UserID,
		&i.Approved,
		&i.Denied,
		&i.RedeemedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const redeemDeviceCode = `-- name: RedeemDeviceCode :exec
UPDATE device_codes
SET redeemed_at = NOW()
WHERE id = $1
  AND tenant_id = $2
  AND redeemed_at IS NULL
`

type RedeemDeviceCodeParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) RedeemDeviceCode(ctx context.Context, arg RedeemDeviceCodeParams) error {
	_, err := q.db.Exec(ctx, redeemDeviceCode, arg.ID, arg.TenantID)
	return err
}

const touchDeviceCodePoll = `-- name: TouchDeviceCodePoll :exec
UPDATE device_codes
SET last_polled_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type TouchDeviceCodePollParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) TouchDeviceCodePoll(ctx context.Context, arg TouchDeviceCodePollParams) error {
	_, err := q.db.Exec(ctx, touchDeviceCodePoll, arg.ID, arg.TenantID)
	return err
}
