// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: federation.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdPConnector = `-- name: CreateIdPConnector :one
INSERT INTO idp_connectors (
    tenant_id, slug, display_name, issuer, client_id,
    secret_ciphertext, dek_ciphertext, scopes, claim_mapping, enabled
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
)
RETURNING id, tenant_id, slug, display_name, issuer, client_id, secret_ciphertext, dek_ciphertext, scopes, claim_mapping, enabled, created_at, updated_at
`

type CreateIdPConnectorParams struct {
	TenantID         uuid.UUID       `db:"tenant_id"`
	Slug             string          `db:"slug"`
	DisplayName      string          `db:"display_name"`
	Issuer           string          `db:"issuer"`
	ClientID         string          `db:"client_id"`
	SecretCiphertext []byte          `db:"secret_ciphertext"`
	DEKCiphertext    []byte          `db:"dek_ciphertext"`
	Scopes           []string        `db:"scopes"`
	ClaimMapping     json.RawMessage `db:"claim_mapping"`
	Enabled          bool            `db:"enabled"`
}

func (q *Queries) CreateIdPConnector(ctx context.Context, arg CreateIdPConnectorParams) (*IdpConnector, error) {
	row := q.db.QueryRow(ctx, createIdPConnector,
		arg.TenantID,
		arg.Slug,
		arg.DisplayName,
		arg.Issuer,
		arg.ClientID,
		arg.SecretCiphertext,
		arg.DEKCiphertext,
		arg.Scopes,
		arg.ClaimMapping,
		arg.Enabled,
	)
	var i IdpConnector
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.SecretCiphertext,
		&i.DEKCiphertext,
		&i.Scopes,
		&i.ClaimMapping,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteIdPConnector = `-- name: DeleteIdPConnector :exec
DELETE FROM idp_connectors
WHERE id = $1 AND tenant_id = $2
`

type DeleteIdPConnectorParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) DeleteIdPConnector(ctx context.Context, arg DeleteIdPConnectorParams) error {
	_, err := q.db.Exec(ctx, deleteIdPConnector, arg.ID, arg.TenantID)
	return err
}

const getAuthRequestByFederationState = `-- name: GetAuthRequestByFederationState :one
SELECT id, tenant_id, client_id, redirect_uri, response_type, response_mode, scopes, state, nonce, code_challenge, code_challenge_method, prompt, max_age, ui_locales, acr_values, login_hint, par_request_uri, request_object_jti, login_session_id, user_id, code_hash, code_issued_at, code_consumed_at, consented_at, created_at, expires_at, federation_idp_id, federation_state, federation_nonce, federation_pkce_verifier FROM auth_requests
WHERE tenant_id = $1 AND federation_state = $2
`

type GetAuthRequestByFederationStateParams struct {
	TenantID        uuid.UUID   `db:"tenant_id"`
	FederationState pgtype.Text `db:"federation_state"`
}

func (q *Queries) GetAuthRequestByFederationState(ctx context.Context, arg GetAuthRequestByFederationStateParams) (*AuthRequest, error) {
	row := q.db.QueryRow(ctx, getAuthRequestByFederationState, arg.TenantID, arg.FederationState)
	var i AuthRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ClientID,
		&i.RedirectUri,
		&i.ResponseType,
		&i.ResponseMode,
		&i.Scopes,
		&i.State,
		&i.Nonce,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.Prompt,
		&i.MaxAge,
		&i.UiLocales,
		&i.AcrValues,
		&i.LoginHint,
		&i.ParRequestUri,
		&i.RequestObjectJti,
		&i.LoginSessionID,
		&i.UserID,
		&i.CodeHash,
		&i.CodeIssuedAt,
		&i.CodeConsumedAt,
		&i.ConsentedAt,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.FederationIdpID,
		&i.FederationState,
		&i.FederationNonce,
		&i.FederationPkceVerifier,
	)
	return &i, err
}

const getFederatedUser = `-- name: GetFederatedUser :one
SELECT id, tenant_id, idp_id, user_id, subject, linked_at, last_login_at FROM federated_identity
WHERE tenant_id = $1 AND idp_id = $2 AND subject = $3
`

type GetFederatedUserParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	IdpID    uuid.UUID `db:"idp_id"`
	Subject  string    `db:"subject"`
}

func (q *Queries) GetFederatedUser(ctx context.Context, arg GetFederatedUserParams) (*FederatedIdentity, error) {
	row := q.db.QueryRow(ctx, getFederatedUser, arg.TenantID, arg.IdpID, arg.Subject)
	var i FederatedIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdpID,
		&i.UserID,
		&i.Subject,
		&i.LinkedAt,
		&i.LastLoginAt,
	)
	return &i, err
}

const getIdPConnectorByID = `-- name: GetIdPConnectorByID :one
SELECT id, tenant_id, slug, display_name, issuer, client_id, secret_ciphertext, dek_ciphertext, scopes, claim_mapping, enabled, created_at, updated_at FROM idp_connectors
WHERE id = $1 AND tenant_id = $2
`

type GetIdPConnectorByIDParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetIdPConnectorByID(ctx context.Context, arg GetIdPConnectorByIDParams) (*IdpConnector, error) {
	row := q.db.QueryRow(ctx, getIdPConnectorByID, arg.ID, arg.TenantID)
	var i IdpConnector
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.SecretCiphertext,
		&i.DEKCiphertext,
		&i.Scopes,
		&i.ClaimMapping,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getIdPConnectorBySlug = `-- name: GetIdPConnectorBySlug :one
SELECT id, tenant_id, slug, display_name, issuer, client_id, secret_ciphertext, dek_ciphertext, scopes, claim_mapping, enabled, created_at, updated_at FROM idp_connectors
WHERE tenant_id = $1 AND slug = $2
`

type GetIdPConnectorBySlugParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	Slug     string    `db:"slug"`
}

func (q *Queries) GetIdPConnectorBySlug(ctx context.Context, arg GetIdPConnectorBySlugParams) (*IdpConnector, error) {
	row := q.db.QueryRow(ctx, getIdPConnectorBySlug, arg.TenantID, arg.Slug)
	var i IdpConnector
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.ClientID,
		&i.SecretCiphertext,
		&i.DEKCiphertext,
		&i.Scopes,
		&i.ClaimMapping,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const linkFederatedIdentity = `-- name: LinkFederatedIdentity :one
INSERT INTO federated_identity (
    tenant_id, idp_id, user_id, subject
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (tenant_id, idp_id, subject) DO UPDATE SET
    last_login_at = NOW()
RETURNING id, tenant_id, idp_id, user_id, subject, linked_at, last_login_at
`

type LinkFederatedIdentityParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	IdpID    uuid.UUID `db:"idp_id"`
	UserID   uuid.UUID `db:"user_id"`
	Subject  string    `db:"subject"`
}

func (q *Queries) LinkFederatedIdentity(ctx context.Context, arg LinkFederatedIdentityParams) (*FederatedIdentity, error) {
	row := q.db.QueryRow(ctx, linkFederatedIdentity,
		arg.TenantID,
		arg.IdpID,
		arg.UserID,
		arg.Subject,
	)
	var i FederatedIdentity
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.IdpID,
		&i.UserID,
		&i.Subject,
		&i.LinkedAt,
		&i.LastLoginAt,
	)
	return &i, err
}

const listEnabledIdPConnectors = `-- name: ListEnabledIdPConnectors :many
SELECT id, tenant_id, slug, display_name, issuer, client_id, secret_ciphertext, dek_ciphertext, scopes, claim_mapping, enabled, created_at, updated_at FROM idp_connectors
WHERE tenant_id = $1 AND enabled = TRUE
ORDER BY display_name ASC
`

func (q *Queries) ListEnabledIdPConnectors(ctx context.Context, tenantID uuid.UUID) ([]*IdpConnector, error) {
	rows, err := q.db.Query(ctx, listEnabledIdPConnectors, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*IdpConnector{}
	for rows.Next() {
		var i IdpConnector
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.DisplayName,
			&i.Issuer,
			&i.ClientID,
			&i.SecretCiphertext,
			&i.DEKCiphertext,
			&i.Scopes,
			&i.ClaimMapping,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFederatedIdentitiesForUser = `-- name: ListFederatedIdentitiesForUser :many
SELECT fi.id, fi.tenant_id, fi.idp_id, fi.user_id, fi.subject, fi.linked_at, fi.last_login_at, ic.slug AS idp_slug, ic.display_name AS idp_display_name
FROM federated_identity fi
JOIN idp_connectors ic ON ic.id = fi.idp_id
WHERE fi.tenant_id = $1 AND fi.user_id = $2
ORDER BY fi.linked_at DESC
`

type ListFederatedIdentitiesForUserParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

type ListFederatedIdentitiesForUserRow struct {
	ID             uuid.UUID          `db:"id"`
	TenantID       uuid.UUID          `db:"tenant_id"`
	IdpID          uuid.UUID          `db:"idp_id"`
	UserID         uuid.UUID          `db:"user_id"`
	Subject        string             `db:"subject"`
	LinkedAt       time.Time          `db:"linked_at"`
	LastLoginAt    pgtype.Timestamptz `db:"last_login_at"`
	IdpSlug        string             `db:"idp_slug"`
	IdpDisplayName string             `db:"idp_display_name"`
}

func (q *Queries) ListFederatedIdentitiesForUser(ctx context.Context, arg ListFederatedIdentitiesForUserParams) ([]*ListFederatedIdentitiesForUserRow, error) {
	rows, err := q.db.Query(ctx, listFederatedIdentitiesForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*ListFederatedIdentitiesForUserRow{}
	for rows.Next() {
		var i ListFederatedIdentitiesForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.IdpID,
			&i.UserID,
			&i.Subject,
			&i.LinkedAt,
			&i.LastLoginAt,
			&i.IdpSlug,
			&i.IdpDisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setAuthRequestFederation = `-- name: SetAuthRequestFederation :exec
UPDATE auth_requests
SET federation_idp_id          = $3,
    federation_state           = $4,
    federation_nonce           = $5,
    federation_pkce_verifier   = $6
WHERE id = $1 AND tenant_id = $2
`

type SetAuthRequestFederationParams struct {
	ID                     uuid.UUID   `db:"id"`
	TenantID               uuid.UUID   `db:"tenant_id"`
	FederationIdpID        pgtype.UUID `db:"federation_idp_id"`
	FederationState        pgtype.Text `db:"federation_state"`
	FederationNonce        pgtype.Text `db:"federation_nonce"`
	FederationPkceVerifier pgtype.Text `db:"federation_pkce_verifier"`
}

func (q *Queries) SetAuthRequestFederation(ctx context.Context, arg SetAuthRequestFederationParams) error {
	_, err := q.db.Exec(ctx, setAuthRequestFederation,
		arg.ID,
		arg.TenantID,
		arg.FederationIdpID,
		arg.FederationState,
		arg.FederationNonce,
		arg.FederationPkceVerifier,
	)
	return err
}

const unlinkFederatedIdentity = `-- name: UnlinkFederatedIdentity :exec
DELETE FROM federated_identity
WHERE id = $1 AND tenant_id = $2
`

type UnlinkFederatedIdentityParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) UnlinkFederatedIdentity(ctx context.Context, arg UnlinkFederatedIdentityParams) error {
	_, err := q.db.Exec(ctx, unlinkFederatedIdentity, arg.ID, arg.TenantID)
	return err
}
