// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jwks.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRetiredJWKSKeys = `-- name: DeleteRetiredJWKSKeys :exec
DELETE FROM jwks_keys
WHERE status = 'retired'
  AND retired_at IS NOT NULL
  AND retired_at < $1
`

// tenantguard: global-ok (background sweep across all tenants; status-driven, not tenant-driven)
func (q *Queries) DeleteRetiredJWKSKeys(ctx context.Context, retiredAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, deleteRetiredJWKSKeys, retiredAt)
	return err
}

const getActiveJWKSKey = `-- name: GetActiveJWKSKey :one
SELECT id, tenant_id, kid, alg, use, public_pem, private_ciphertext, dek_ciphertext, status, created_at, rotated_at, retired_at FROM jwks_keys
WHERE (tenant_id = $1 OR tenant_id IS NULL)
  AND use = $2
  AND status = 'active'
ORDER BY tenant_id NULLS LAST, created_at DESC
LIMIT 1
`

type GetActiveJWKSKeyParams struct {
	TenantID pgtype.UUID `db:"tenant_id"`
	Use      string      `db:"use"`
}

func (q *Queries) GetActiveJWKSKey(ctx context.Context, arg GetActiveJWKSKeyParams) (*JwksKey, error) {
	row := q.db.QueryRow(ctx, getActiveJWKSKey, arg.TenantID, arg.Use)
	var i JwksKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KID,
		&i.Alg,
		&i.Use,
		&i.PublicPem,
		&i.PrivateCiphertext,
		&i.DEKCiphertext,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RetiredAt,
	)
	return &i, err
}

const getJWKSKeyByKID = `-- name: GetJWKSKeyByKID :one
SELECT id, tenant_id, kid, alg, use, public_pem, private_ciphertext, dek_ciphertext, status, created_at, rotated_at, retired_at FROM jwks_keys
WHERE kid = $1
`

// tenantguard: global-ok (kid is a SHA-256 hash and globally unique by construction; verifiers may not know the tenant yet)
func (q *Queries) GetJWKSKeyByKID(ctx context.Context, kid string) (*JwksKey, error) {
	row := q.db.QueryRow(ctx, getJWKSKeyByKID, kid)
	var i JwksKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KID,
		&i.Alg,
		&i.Use,
		&i.PublicPem,
		&i.PrivateCiphertext,
		&i.DEKCiphertext,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RetiredAt,
	)
	return &i, err
}

const insertJWKSKey = `-- name: InsertJWKSKey :one
INSERT INTO jwks_keys (
    tenant_id, kid, alg, use, public_pem,
    private_ciphertext, dek_ciphertext, status,
    created_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8,
    $9
)
RETURNING id, tenant_id, kid, alg, use, public_pem, private_ciphertext, dek_ciphertext, status, created_at, rotated_at, retired_at
`

type InsertJWKSKeyParams struct {
	TenantID          pgtype.UUID `db:"tenant_id"`
	KID               string      `db:"kid"`
	Alg               string      `db:"alg"`
	Use               string      `db:"use"`
	PublicPem         string      `db:"public_pem"`
	PrivateCiphertext []byte      `db:"private_ciphertext"`
	DEKCiphertext     []byte      `db:"dek_ciphertext"`
	Status            string      `db:"status"`
	CreatedAt         time.Time   `db:"created_at"`
}

func (q *Queries) InsertJWKSKey(ctx context.Context, arg InsertJWKSKeyParams) (*JwksKey, error) {
	row := q.db.QueryRow(ctx, insertJWKSKey,
		arg.TenantID,
		arg.KID,
		arg.Alg,
		arg.Use,
		arg.PublicPem,
		arg.PrivateCiphertext,
		arg.DEKCiphertext,
		arg.Status,
		arg.CreatedAt,
	)
	var i JwksKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.KID,
		&i.Alg,
		&i.Use,
		&i.PublicPem,
		&i.PrivateCiphertext,
		&i.DEKCiphertext,
		&i.Status,
		&i.CreatedAt,
		&i.RotatedAt,
		&i.RetiredAt,
	)
	return &i, err
}

const listAllJWKSKeys = `-- name: ListAllJWKSKeys :many
SELECT id, tenant_id, kid, alg, use, public_pem, private_ciphertext, dek_ciphertext, status, created_at, rotated_at, retired_at FROM jwks_keys
WHERE (tenant_id = $1 OR tenant_id IS NULL)
ORDER BY created_at DESC
`

func (q *Queries) ListAllJWKSKeys(ctx context.Context, tenantID pgtype.UUID) ([]*JwksKey, error) {
	rows, err := q.db.Query(ctx, listAllJWKSKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*JwksKey{}
	for rows.Next() {
		var i JwksKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KID,
			&i.Alg,
			&i.Use,
			&i.PublicPem,
			&i.PrivateCiphertext,
			&i.DEKCiphertext,
			&i.Status,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicJWKSKeys = `-- name: ListPublicJWKSKeys :many
SELECT id, tenant_id, kid, alg, use, public_pem, private_ciphertext, dek_ciphertext, status, created_at, rotated_at, retired_at FROM jwks_keys
WHERE (tenant_id = $1 OR tenant_id IS NULL)
  AND status IN ('active', 'rotated')
ORDER BY created_at DESC
`

func (q *Queries) ListPublicJWKSKeys(ctx context.Context, tenantID pgtype.UUID) ([]*JwksKey, error) {
	rows, err := q.db.Query(ctx, listPublicJWKSKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*JwksKey{}
	for rows.Next() {
		var i JwksKey
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.KID,
			&i.Alg,
			&i.Use,
			&i.PublicPem,
			&i.PrivateCiphertext,
			&i.DEKCiphertext,
			&i.Status,
			&i.CreatedAt,
			&i.RotatedAt,
			&i.RetiredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJWKSKeyRotated = `-- name: MarkJWKSKeyRotated :exec
UPDATE jwks_keys
SET status = 'rotated',
    rotated_at = $2
WHERE id = $1
  AND status = 'active'
`

type MarkJWKSKeyRotatedParams struct {
	ID        uuid.UUID          `db:"id"`
	RotatedAt pgtype.Timestamptz `db:"rotated_at"`
}

// tenantguard: global-ok (called inside Rotate's tx, key was just read by id with tenant filter applied)
func (q *Queries) MarkJWKSKeyRotated(ctx context.Context, arg MarkJWKSKeyRotatedParams) error {
	_, err := q.db.Exec(ctx, markJWKSKeyRotated, arg.ID, arg.RotatedAt)
	return err
}

const retireJWKSKeysOlderThan = `-- name: RetireJWKSKeysOlderThan :exec
UPDATE jwks_keys
SET status = 'retired',
    retired_at = $2
WHERE status = 'rotated'
  AND rotated_at IS NOT NULL
  AND rotated_at < $1
`

type RetireJWKSKeysOlderThanParams struct {
	RotatedAt pgtype.Timestamptz `db:"rotated_at"`
	RetiredAt pgtype.Timestamptz `db:"retired_at"`
}

// tenantguard: global-ok (background sweep across all tenants; status-driven, not tenant-driven)
func (q *Queries) RetireJWKSKeysOlderThan(ctx context.Context, arg RetireJWKSKeysOlderThanParams) error {
	_, err := q.db.Exec(ctx, retireJWKSKeysOlderThan, arg.RotatedAt, arg.RetiredAt)
	return err
}
