// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mfa.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmUserTOTP = `-- name: ConfirmUserTOTP :exec
UPDATE user_mfa_totp
SET confirmed_at = COALESCE(confirmed_at, NOW()),
    last_used_at = NOW(),
    last_counter = $3
WHERE user_id   = $1
  AND tenant_id = $2
`

type ConfirmUserTOTPParams struct {
	UserID      uuid.UUID   `db:"user_id"`
	TenantID    uuid.UUID   `db:"tenant_id"`
	LastCounter pgtype.Int8 `db:"last_counter"`
}

func (q *Queries) ConfirmUserTOTP(ctx context.Context, arg ConfirmUserTOTPParams) error {
	_, err := q.db.Exec(ctx, confirmUserTOTP, arg.UserID, arg.TenantID, arg.LastCounter)
	return err
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :one
UPDATE user_recovery_codes
SET used_at = NOW()
WHERE tenant_id = $1
  AND user_id   = $2
  AND code_hash = $3
  AND used_at IS NULL
RETURNING id, tenant_id, user_id, code_hash, used_at, created_at
`

type ConsumeRecoveryCodeParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
	CodeHash string    `db:"code_hash"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (*UserRecoveryCode, error) {
	row := q.db.QueryRow(ctx, consumeRecoveryCode, arg.TenantID, arg.UserID, arg.CodeHash)
	var i UserRecoveryCode
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CodeHash,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const consumeWebAuthnChallenge = `-- name: ConsumeWebAuthnChallenge :one
DELETE FROM webauthn_challenges
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, user_id, ceremony, session_data, created_at, expires_at
`

type ConsumeWebAuthnChallengeParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) ConsumeWebAuthnChallenge(ctx context.Context, arg ConsumeWebAuthnChallengeParams) (*WebauthnChallenge, error) {
	row := q.db.QueryRow(ctx, consumeWebAuthnChallenge, arg.ID, arg.TenantID)
	var i WebauthnChallenge
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Ceremony,
		&i.SessionData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const countActiveRecoveryCodes = `-- name: CountActiveRecoveryCodes :one
SELECT COUNT(*) FROM user_recovery_codes
WHERE tenant_id = $1
  AND user_id   = $2
  AND used_at IS NULL
`

type CountActiveRecoveryCodesParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

func (q *Queries) CountActiveRecoveryCodes(ctx context.Context, arg CountActiveRecoveryCodesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveRecoveryCodes, arg.TenantID, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteRecoveryCodesForUser = `-- name: DeleteRecoveryCodesForUser :exec
DELETE FROM user_recovery_codes
WHERE tenant_id = $1
  AND user_id   = $2
`

type DeleteRecoveryCodesForUserParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

func (q *Queries) DeleteRecoveryCodesForUser(ctx context.Context, arg DeleteRecoveryCodesForUserParams) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodesForUser, arg.TenantID, arg.UserID)
	return err
}

const deleteUserTOTP = `-- name: DeleteUserTOTP :exec
DELETE FROM user_mfa_totp
WHERE user_id   = $1
  AND tenant_id = $2
`

type DeleteUserTOTPParams struct {
	UserID   uuid.UUID `db:"user_id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) DeleteUserTOTP(ctx context.Context, arg DeleteUserTOTPParams) error {
	_, err := q.db.Exec(ctx, deleteUserTOTP, arg.UserID, arg.TenantID)
	return err
}

const deleteWebAuthnCredential = `-- name: DeleteWebAuthnCredential :exec
DELETE FROM user_webauthn_credentials
WHERE id = $1
  AND tenant_id = $2
`

type DeleteWebAuthnCredentialParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error {
	_, err := q.db.Exec(ctx, deleteWebAuthnCredential, arg.ID, arg.TenantID)
	return err
}

const getUserTOTP = `-- name: GetUserTOTP :one
SELECT user_id, tenant_id, secret_ciphertext, dek_ciphertext, algorithm, digits, period_seconds, confirmed_at, last_used_at, last_counter, created_at FROM user_mfa_totp
WHERE user_id   = $1
  AND tenant_id = $2
`

type GetUserTOTPParams struct {
	UserID   uuid.UUID `db:"user_id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetUserTOTP(ctx context.Context, arg GetUserTOTPParams) (*UserMfaTotp, error) {
	row := q.db.QueryRow(ctx, getUserTOTP, arg.UserID, arg.TenantID)
	var i UserMfaTotp
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.SecretCiphertext,
		&i.DEKCiphertext,
		&i.Algorithm,
		&i.Digits,
		&i.PeriodSeconds,
		&i.ConfirmedAt,
		&i.LastUsedAt,
		&i.LastCounter,
		&i.CreatedAt,
	)
	return &i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO user_recovery_codes (tenant_id, user_id, code_hash)
VALUES ($1, $2, $3)
`

type InsertRecoveryCodeParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
	CodeHash string    `db:"code_hash"`
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.TenantID, arg.UserID, arg.CodeHash)
	return err
}

const insertWebAuthnChallenge = `-- name: InsertWebAuthnChallenge :one
INSERT INTO webauthn_challenges (
    tenant_id, user_id, ceremony, session_data, expires_at
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, tenant_id, user_id, ceremony, session_data, created_at, expires_at
`

type InsertWebAuthnChallengeParams struct {
	TenantID    uuid.UUID       `db:"tenant_id"`
	UserID      pgtype.UUID     `db:"user_id"`
	Ceremony    string          `db:"ceremony"`
	SessionData json.RawMessage `db:"session_data"`
	ExpiresAt   time.Time       `db:"expires_at"`
}

func (q *Queries) InsertWebAuthnChallenge(ctx context.Context, arg InsertWebAuthnChallengeParams) (*WebauthnChallenge, error) {
	row := q.db.QueryRow(ctx, insertWebAuthnChallenge,
		arg.TenantID,
		arg.UserID,
		arg.Ceremony,
		arg.SessionData,
		arg.ExpiresAt,
	)
	var i WebauthnChallenge
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Ceremony,
		&i.SessionData,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return &i, err
}

const insertWebAuthnCredential = `-- name: InsertWebAuthnCredential :one
INSERT INTO user_webauthn_credentials (
    tenant_id, user_id, credential_id, public_key, sign_count,
    aaguid, transports, attestation_type, nickname
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, tenant_id, user_id, credential_id, public_key, sign_count, aaguid, transports, attestation_type, nickname, created_at, last_used_at
`

type InsertWebAuthnCredentialParams struct {
	TenantID        uuid.UUID   `db:"tenant_id"`
	UserID          uuid.UUID   `db:"user_id"`
	CredentialID    []byte      `db:"credential_id"`
	PublicKey       []byte      `db:"public_key"`
	SignCount       int64       `db:"sign_count"`
	Aaguid          []byte      `db:"aaguid"`
	Transports      []string    `db:"transports"`
	AttestationType pgtype.Text `db:"attestation_type"`
	Nickname        pgtype.Text `db:"nickname"`
}

func (q *Queries) InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) (*UserWebauthnCredential, error) {
	row := q.db.QueryRow(ctx, insertWebAuthnCredential,
		arg.TenantID,
		arg.UserID,
		arg.CredentialID,
		arg.PublicKey,
		arg.SignCount,
		arg.Aaguid,
		arg.Transports,
		arg.AttestationType,
		arg.Nickname,
	)
	var i UserWebauthnCredential
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CredentialID,
		&i.PublicKey,
		&i.SignCount,
		&i.Aaguid,
		&i.Transports,
		&i.AttestationType,
		&i.Nickname,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return &i, err
}

const listActiveRecoveryCodes = `-- name: ListActiveRecoveryCodes :many
SELECT id, tenant_id, user_id, code_hash, used_at, created_at FROM user_recovery_codes
WHERE tenant_id = $1
  AND user_id   = $2
  AND used_at IS NULL
ORDER BY created_at ASC
`

type ListActiveRecoveryCodesParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

func (q *Queries) ListActiveRecoveryCodes(ctx context.Context, arg ListActiveRecoveryCodesParams) ([]*UserRecoveryCode, error) {
	rows, err := q.db.Query(ctx, listActiveRecoveryCodes, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserRecoveryCode{}
	for rows.Next() {
		var i UserRecoveryCode
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.CodeHash,
			&i.UsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWebAuthnCredentialsForUser = `-- name: ListWebAuthnCredentialsForUser :many
SELECT id, tenant_id, user_id, credential_id, public_key, sign_count, aaguid, transports, attestation_type, nickname, created_at, last_used_at FROM user_webauthn_credentials
WHERE tenant_id = $1
  AND user_id   = $2
ORDER BY created_at DESC
`

type ListWebAuthnCredentialsForUserParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

func (q *Queries) ListWebAuthnCredentialsForUser(ctx context.Context, arg ListWebAuthnCredentialsForUserParams) ([]*UserWebauthnCredential, error) {
	rows, err := q.db.Query(ctx, listWebAuthnCredentialsForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*UserWebauthnCredential{}
	for rows.Next() {
		var i UserWebauthnCredential
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.CredentialID,
			&i.PublicKey,
			&i.SignCount,
			&i.Aaguid,
			&i.Transports,
			&i.AttestationType,
			&i.Nickname,
			&i.CreatedAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchUserTOTP = `-- name: TouchUserTOTP :exec
UPDATE user_mfa_totp
SET last_used_at = NOW(),
    last_counter = $3
WHERE user_id   = $1
  AND tenant_id = $2
`

type TouchUserTOTPParams struct {
	UserID      uuid.UUID   `db:"user_id"`
	TenantID    uuid.UUID   `db:"tenant_id"`
	LastCounter pgtype.Int8 `db:"last_counter"`
}

func (q *Queries) TouchUserTOTP(ctx context.Context, arg TouchUserTOTPParams) error {
	_, err := q.db.Exec(ctx, touchUserTOTP, arg.UserID, arg.TenantID, arg.LastCounter)
	return err
}

const updateWebAuthnSignCount = `-- name: UpdateWebAuthnSignCount :exec
UPDATE user_webauthn_credentials
SET sign_count   = $3,
    last_used_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type UpdateWebAuthnSignCountParams struct {
	ID        uuid.UUID `db:"id"`
	TenantID  uuid.UUID `db:"tenant_id"`
	SignCount int64     `db:"sign_count"`
}

func (q *Queries) UpdateWebAuthnSignCount(ctx context.Context, arg UpdateWebAuthnSignCountParams) error {
	_, err := q.db.Exec(ctx, updateWebAuthnSignCount, arg.ID, arg.TenantID, arg.SignCount)
	return err
}

const upsertUserTOTP = `-- name: UpsertUserTOTP :exec
INSERT INTO user_mfa_totp (
    user_id, tenant_id, secret_ciphertext, dek_ciphertext,
    algorithm, digits, period_seconds
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (user_id) DO UPDATE SET
    secret_ciphertext = EXCLUDED.secret_ciphertext,
    dek_ciphertext    = EXCLUDED.dek_ciphertext,
    algorithm         = EXCLUDED.algorithm,
    digits            = EXCLUDED.digits,
    period_seconds    = EXCLUDED.period_seconds,
    confirmed_at      = NULL,
    last_counter      = NULL
`

type UpsertUserTOTPParams struct {
	UserID           uuid.UUID `db:"user_id"`
	TenantID         uuid.UUID `db:"tenant_id"`
	SecretCiphertext []byte    `db:"secret_ciphertext"`
	DEKCiphertext    []byte    `db:"dek_ciphertext"`
	Algorithm        string    `db:"algorithm"`
	Digits           int32     `db:"digits"`
	PeriodSeconds    int32     `db:"period_seconds"`
}

func (q *Queries) UpsertUserTOTP(ctx context.Context, arg UpsertUserTOTPParams) error {
	_, err := q.db.Exec(ctx, upsertUserTOTP,
		arg.UserID,
		arg.TenantID,
		arg.SecretCiphertext,
		arg.DEKCiphertext,
		arg.Algorithm,
		arg.Digits,
		arg.PeriodSeconds,
	)
	return err
}
