// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessToken struct {
	ID         uuid.UUID          `db:"id"`
	TenantID   uuid.UUID          `db:"tenant_id"`
	TokenHash  string             `db:"token_hash"`
	ClientID   uuid.UUID          `db:"client_id"`
	UserID     pgtype.UUID        `db:"user_id"`
	Scopes     []string           `db:"scopes"`
	Audience   []string           `db:"audience"`
	CnfJkt     pgtype.Text        `db:"cnf_jkt"`
	CnfX5tS256 pgtype.Text        `db:"cnf_x5t_s256"`
	SessionID  pgtype.UUID        `db:"session_id"`
	IssuedAt   time.Time          `db:"issued_at"`
	ExpiresAt  time.Time          `db:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at"`
}

type AccountLockout struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	EmailHash []byte    `db:"email_hash"`
	LockedAt  time.Time `db:"locked_at"`
	UnlockAt  time.Time `db:"unlock_at"`
	Reason    string    `db:"reason"`
}

type AuditLog struct {
	ID            int64           `db:"id"`
	TenantID      uuid.UUID       `db:"tenant_id"`
	ActorUserID   pgtype.UUID     `db:"actor_user_id"`
	ActorClientID pgtype.UUID     `db:"actor_client_id"`
	Action        string          `db:"action"`
	TargetType    string          `db:"target_type"`
	TargetID      pgtype.Text     `db:"target_id"`
	Ip            pgtype.Text     `db:"ip"`
	UserAgent     pgtype.Text     `db:"user_agent"`
	RequestID     pgtype.Text     `db:"request_id"`
	Attributes    json.RawMessage `db:"attributes"`
	OccurredAt    time.Time       `db:"occurred_at"`
}

type AuthRequest struct {
	ID                     uuid.UUID          `db:"id"`
	TenantID               uuid.UUID          `db:"tenant_id"`
	ClientID               uuid.UUID          `db:"client_id"`
	RedirectUri            string             `db:"redirect_uri"`
	ResponseType           string             `db:"response_type"`
	ResponseMode           pgtype.Text        `db:"response_mode"`
	Scopes                 []string           `db:"scopes"`
	State                  pgtype.Text        `db:"state"`
	Nonce                  pgtype.Text        `db:"nonce"`
	CodeChallenge          pgtype.Text        `db:"code_challenge"`
	CodeChallengeMethod    pgtype.Text        `db:"code_challenge_method"`
	Prompt                 []string           `db:"prompt"`
	MaxAge                 pgtype.Int4        `db:"max_age"`
	UiLocales              pgtype.Text        `db:"ui_locales"`
	AcrValues              pgtype.Text        `db:"acr_values"`
	LoginHint              pgtype.Text        `db:"login_hint"`
	ParRequestUri          pgtype.Text        `db:"par_request_uri"`
	RequestObjectJti       pgtype.Text        `db:"request_object_jti"`
	LoginSessionID         pgtype.UUID        `db:"login_session_id"`
	UserID                 pgtype.UUID        `db:"user_id"`
	CodeHash               pgtype.Text        `db:"code_hash"`
	CodeIssuedAt           pgtype.Timestamptz `db:"code_issued_at"`
	CodeConsumedAt         pgtype.Timestamptz `db:"code_consumed_at"`
	ConsentedAt            pgtype.Timestamptz `db:"consented_at"`
	CreatedAt              time.Time          `db:"created_at"`
	ExpiresAt              time.Time          `db:"expires_at"`
	FederationIdpID        pgtype.UUID        `db:"federation_idp_id"`
	FederationState        pgtype.Text        `db:"federation_state"`
	FederationNonce        pgtype.Text        `db:"federation_nonce"`
	FederationPkceVerifier pgtype.Text        `db:"federation_pkce_verifier"`
}

type CibaRequest struct {
	ID              uuid.UUID          `db:"id"`
	TenantID        uuid.UUID          `db:"tenant_id"`
	ClientID        uuid.UUID          `db:"client_id"`
	AuthReqID       string             `db:"auth_req_id"`
	UserID          pgtype.UUID        `db:"user_id"`
	BindingMessage  pgtype.Text        `db:"binding_message"`
	Scopes          []string           `db:"scopes"`
	Audience        []string           `db:"audience"`
	AcrValues       pgtype.Text        `db:"acr_values"`
	IntervalSeconds int32              `db:"interval_seconds"`
	LastPolledAt    pgtype.Timestamptz `db:"last_polled_at"`
	Status          string             `db:"status"`
	CreatedAt       time.Time          `db:"created_at"`
	ExpiresAt       time.Time          `db:"expires_at"`
}

type Client struct {
	ID                                    uuid.UUID   `db:"id"`
	TenantID                              uuid.UUID   `db:"tenant_id"`
	ClientID                              string      `db:"client_id"`
	ClientSecretHash                      pgtype.Text `db:"client_secret_hash"`
	ClientType                            string      `db:"client_type"`
	Name                                  string      `db:"name"`
	Description                           pgtype.Text `db:"description"`
	GrantTypes                            []string    `db:"grant_types"`
	ResponseTypes                         []string    `db:"response_types"`
	ResponseModes                         []string    `db:"response_modes"`
	Scopes                                []string    `db:"scopes"`
	TokenEndpointAuthMethod               string      `db:"token_endpoint_auth_method"`
	TokenEndpointAuthSigningAlg           pgtype.Text `db:"token_endpoint_auth_signing_alg"`
	RequestObjectSigningAlg               pgtype.Text `db:"request_object_signing_alg"`
	RequireSignedRequestObject            bool        `db:"require_signed_request_object"`
	RequirePAR                            bool        `db:"require_par"`
	RequireDPoP                           bool        `db:"require_dpop"`
	DPoPBoundAccessTokens                 bool        `db:"dpop_bound_access_tokens"`
	TLSClientAuthSubjectDN                pgtype.Text `db:"tls_client_auth_subject_dn"`
	TLSClientCertificateBoundAccessTokens bool        `db:"tls_client_certificate_bound_access_tokens"`
	AuthorizationSignedResponseAlg        pgtype.Text `db:"authorization_signed_response_alg"`
	JWKSURI                               pgtype.Text `db:"jwks_uri"`
	Jwks                                  []byte      `db:"jwks"`
	BackchannelTokenDeliveryMode          pgtype.Text `db:"backchannel_token_delivery_mode"`
	BackchannelClientNotificationEndpoint pgtype.Text `db:"backchannel_client_notification_endpoint"`
	IsFederationClient                    bool        `db:"is_federation_client"`
	Enabled                               bool        `db:"enabled"`
	CreatedAt                             time.Time   `db:"created_at"`
	UpdatedAt                             time.Time   `db:"updated_at"`
}

type ClientAllowedResource struct {
	ID       int64     `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
	ClientID uuid.UUID `db:"client_id"`
	Resource string    `db:"resource"`
}

type ClientRedirectUri struct {
	ID          int64     `db:"id"`
	TenantID    uuid.UUID `db:"tenant_id"`
	ClientID    uuid.UUID `db:"client_id"`
	RedirectUri string    `db:"redirect_uri"`
}

type DeviceCode struct {
	ID              uuid.UUID          `db:"id"`
	TenantID        uuid.UUID          `db:"tenant_id"`
	ClientID        uuid.UUID          `db:"client_id"`
	DeviceCode      string             `db:"device_code"`
	UserCode        string             `db:"user_code"`
	Scopes          []string           `db:"scopes"`
	Audience        []string           `db:"audience"`
	IntervalSeconds int32              `db:"interval_seconds"`
	LastPolledAt    pgtype.Timestamptz `db:"last_polled_at"`
	UserID          pgtype.UUID        `db:"user_id"`
	Approved        bool               `db:"approved"`
	Denied          bool               `db:"denied"`
	RedeemedAt      pgtype.Timestamptz `db:"redeemed_at"`
	CreatedAt       time.Time          `db:"created_at"`
	ExpiresAt       time.Time          `db:"expires_at"`
}

type FederatedIdentity struct {
	ID          uuid.UUID          `db:"id"`
	TenantID    uuid.UUID          `db:"tenant_id"`
	IdpID       uuid.UUID          `db:"idp_id"`
	UserID      uuid.UUID          `db:"user_id"`
	Subject     string             `db:"subject"`
	LinkedAt    time.Time          `db:"linked_at"`
	LastLoginAt pgtype.Timestamptz `db:"last_login_at"`
}

type IdpConnector struct {
	ID               uuid.UUID       `db:"id"`
	TenantID         uuid.UUID       `db:"tenant_id"`
	Slug             string          `db:"slug"`
	DisplayName      string          `db:"display_name"`
	Issuer           string          `db:"issuer"`
	ClientID         string          `db:"client_id"`
	SecretCiphertext []byte          `db:"secret_ciphertext"`
	DEKCiphertext    []byte          `db:"dek_ciphertext"`
	Scopes           []string        `db:"scopes"`
	ClaimMapping     json.RawMessage `db:"claim_mapping"`
	Enabled          bool            `db:"enabled"`
	CreatedAt        time.Time       `db:"created_at"`
	UpdatedAt        time.Time       `db:"updated_at"`
}

type JwksKey struct {
	ID                uuid.UUID          `db:"id"`
	TenantID          pgtype.UUID        `db:"tenant_id"`
	KID               string             `db:"kid"`
	Alg               string             `db:"alg"`
	Use               string             `db:"use"`
	PublicPem         string             `db:"public_pem"`
	PrivateCiphertext []byte             `db:"private_ciphertext"`
	DEKCiphertext     []byte             `db:"dek_ciphertext"`
	Status            string             `db:"status"`
	CreatedAt         time.Time          `db:"created_at"`
	RotatedAt         pgtype.Timestamptz `db:"rotated_at"`
	RetiredAt         pgtype.Timestamptz `db:"retired_at"`
}

type LoginFailure struct {
	ID         int64       `db:"id"`
	TenantID   uuid.UUID   `db:"tenant_id"`
	EmailHash  []byte      `db:"email_hash"`
	Ip         pgtype.Text `db:"ip"`
	OccurredAt time.Time   `db:"occurred_at"`
}

type ParRequest struct {
	ID         uuid.UUID          `db:"id"`
	TenantID   uuid.UUID          `db:"tenant_id"`
	RequestUri string             `db:"request_uri"`
	ClientID   uuid.UUID          `db:"client_id"`
	Payload    json.RawMessage    `db:"payload"`
	CreatedAt  time.Time          `db:"created_at"`
	ExpiresAt  time.Time          `db:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at"`
}

type RateBucket struct {
	Endpoint  string    `db:"endpoint"`
	Key       string    `db:"key"`
	Level     float64   `db:"level"`
	UpdatedAt time.Time `db:"updated_at"`
}

type RefreshToken struct {
	ID         uuid.UUID          `db:"id"`
	TenantID   uuid.UUID          `db:"tenant_id"`
	TokenHash  string             `db:"token_hash"`
	ClientID   uuid.UUID          `db:"client_id"`
	UserID     uuid.UUID          `db:"user_id"`
	Scopes     []string           `db:"scopes"`
	FamilyID   uuid.UUID          `db:"family_id"`
	ParentID   pgtype.UUID        `db:"parent_id"`
	CnfJkt     pgtype.Text        `db:"cnf_jkt"`
	CnfX5tS256 pgtype.Text        `db:"cnf_x5t_s256"`
	IssuedAt   time.Time          `db:"issued_at"`
	ExpiresAt  time.Time          `db:"expires_at"`
	ConsumedAt pgtype.Timestamptz `db:"consumed_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at"`
}

type Role struct {
	ID          uuid.UUID `db:"id"`
	Name        string    `db:"name"`
	Description string    `db:"description"`
	Permissions []string  `db:"permissions"`
	CreatedAt   time.Time `db:"created_at"`
}

type SchemaMetum struct {
	Singleton bool      `db:"singleton"`
	Version   string    `db:"version"`
	AppliedAt time.Time `db:"applied_at"`
}

type Session struct {
	ID         uuid.UUID          `db:"id"`
	TenantID   uuid.UUID          `db:"tenant_id"`
	UserID     uuid.UUID          `db:"user_id"`
	CsrfSecret string             `db:"csrf_secret"`
	Ip         pgtype.Text        `db:"ip"`
	UserAgent  pgtype.Text        `db:"user_agent"`
	MfaLevel   string             `db:"mfa_level"`
	Amr        []string           `db:"amr"`
	AuthTime   time.Time          `db:"auth_time"`
	LastSeenAt time.Time          `db:"last_seen_at"`
	ExpiresAt  time.Time          `db:"expires_at"`
	RevokedAt  pgtype.Timestamptz `db:"revoked_at"`
}

type Tenant struct {
	ID          uuid.UUID `db:"id"`
	Slug        string    `db:"slug"`
	DisplayName string    `db:"display_name"`
	Issuer      string    `db:"issuer"`
	Enabled     bool      `db:"enabled"`
	CreatedAt   time.Time `db:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `db:"id"`
	TenantID      uuid.UUID          `db:"tenant_id"`
	Email         string             `db:"email"`
	EmailVerified bool               `db:"email_verified"`
	DisplayName   pgtype.Text        `db:"display_name"`
	Locale        pgtype.Text        `db:"locale"`
	Zoneinfo      pgtype.Text        `db:"zoneinfo"`
	PictureUrl    pgtype.Text        `db:"picture_url"`
	Enabled       bool               `db:"enabled"`
	CreatedAt     time.Time          `db:"created_at"`
	UpdatedAt     time.Time          `db:"updated_at"`
	DeletedAt     pgtype.Timestamptz `db:"deleted_at"`
}

type UserConsent struct {
	ID        uuid.UUID          `db:"id"`
	TenantID  uuid.UUID          `db:"tenant_id"`
	UserID    uuid.UUID          `db:"user_id"`
	ClientID  uuid.UUID          `db:"client_id"`
	Scopes    []string           `db:"scopes"`
	GrantedAt time.Time          `db:"granted_at"`
	RevokedAt pgtype.Timestamptz `db:"revoked_at"`
}

type UserCredential struct {
	UserID       uuid.UUID `db:"user_id"`
	TenantID     uuid.UUID `db:"tenant_id"`
	PasswordHash string    `db:"password_hash"`
	Algorithm    string    `db:"algorithm"`
	MustChange   bool      `db:"must_change"`
	UpdatedAt    time.Time `db:"updated_at"`
}

type UserMfaTotp struct {
	UserID           uuid.UUID          `db:"user_id"`
	TenantID         uuid.UUID          `db:"tenant_id"`
	SecretCiphertext []byte             `db:"secret_ciphertext"`
	DEKCiphertext    []byte             `db:"dek_ciphertext"`
	Algorithm        string             `db:"algorithm"`
	Digits           int32              `db:"digits"`
	PeriodSeconds    int32              `db:"period_seconds"`
	ConfirmedAt      pgtype.Timestamptz `db:"confirmed_at"`
	LastUsedAt       pgtype.Timestamptz `db:"last_used_at"`
	LastCounter      pgtype.Int8        `db:"last_counter"`
	CreatedAt        time.Time          `db:"created_at"`
}

type UserRecoveryCode struct {
	ID        uuid.UUID          `db:"id"`
	TenantID  uuid.UUID          `db:"tenant_id"`
	UserID    uuid.UUID          `db:"user_id"`
	CodeHash  string             `db:"code_hash"`
	UsedAt    pgtype.Timestamptz `db:"used_at"`
	CreatedAt time.Time          `db:"created_at"`
}

type UserRole struct {
	ID        uuid.UUID `db:"id"`
	TenantID  uuid.UUID `db:"tenant_id"`
	UserID    uuid.UUID `db:"user_id"`
	RoleID    uuid.UUID `db:"role_id"`
	GrantedAt time.Time `db:"granted_at"`
}

type UserWebauthnCredential struct {
	ID              uuid.UUID          `db:"id"`
	TenantID        uuid.UUID          `db:"tenant_id"`
	UserID          uuid.UUID          `db:"user_id"`
	CredentialID    []byte             `db:"credential_id"`
	PublicKey       []byte             `db:"public_key"`
	SignCount       int64              `db:"sign_count"`
	Aaguid          []byte             `db:"aaguid"`
	Transports      []string           `db:"transports"`
	AttestationType pgtype.Text        `db:"attestation_type"`
	Nickname        pgtype.Text        `db:"nickname"`
	CreatedAt       time.Time          `db:"created_at"`
	LastUsedAt      pgtype.Timestamptz `db:"last_used_at"`
}

type WebauthnChallenge struct {
	ID          uuid.UUID       `db:"id"`
	TenantID    uuid.UUID       `db:"tenant_id"`
	UserID      pgtype.UUID     `db:"user_id"`
	Ceremony    string          `db:"ceremony"`
	SessionData json.RawMessage `db:"session_data"`
	CreatedAt   time.Time       `db:"created_at"`
	ExpiresAt   time.Time       `db:"expires_at"`
}
