// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: par.sql

package db

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const deleteExpiredPARRequests = `-- name: DeleteExpiredPARRequests :exec
DELETE FROM par_requests
WHERE expires_at < $1
`

// tenantguard: global-ok (background sweep across tenants; status-driven)
func (q *Queries) DeleteExpiredPARRequests(ctx context.Context, expiresAt time.Time) error {
	_, err := q.db.Exec(ctx, deleteExpiredPARRequests, expiresAt)
	return err
}

const getPARRequest = `-- name: GetPARRequest :one
SELECT id, tenant_id, request_uri, client_id, payload, created_at, expires_at, consumed_at FROM par_requests
WHERE request_uri = $1
  AND tenant_id   = $2
FOR UPDATE
`

type GetPARRequestParams struct {
	RequestUri string    `db:"request_uri"`
	TenantID   uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetPARRequest(ctx context.Context, arg GetPARRequestParams) (*ParRequest, error) {
	row := q.db.QueryRow(ctx, getPARRequest, arg.RequestUri, arg.TenantID)
	var i ParRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequestUri,
		&i.ClientID,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return &i, err
}

const insertPARRequest = `-- name: InsertPARRequest :one
INSERT INTO par_requests (tenant_id, request_uri, client_id, payload, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, request_uri, client_id, payload, created_at, expires_at, consumed_at
`

type InsertPARRequestParams struct {
	TenantID   uuid.UUID       `db:"tenant_id"`
	RequestUri string          `db:"request_uri"`
	ClientID   uuid.UUID       `db:"client_id"`
	Payload    json.RawMessage `db:"payload"`
	ExpiresAt  time.Time       `db:"expires_at"`
}

func (q *Queries) InsertPARRequest(ctx context.Context, arg InsertPARRequestParams) (*ParRequest, error) {
	row := q.db.QueryRow(ctx, insertPARRequest,
		arg.TenantID,
		arg.RequestUri,
		arg.ClientID,
		arg.Payload,
		arg.ExpiresAt,
	)
	var i ParRequest
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RequestUri,
		&i.ClientID,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return &i, err
}

const markPARRequestConsumed = `-- name: MarkPARRequestConsumed :exec
UPDATE par_requests
SET consumed_at = NOW()
WHERE id = $1
  AND tenant_id = $2
  AND consumed_at IS NULL
`

type MarkPARRequestConsumedParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) MarkPARRequestConsumed(ctx context.Context, arg MarkPARRequestConsumedParams) error {
	_, err := q.db.Exec(ctx, markPARRequestConsumed, arg.ID, arg.TenantID)
	return err
}
