// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddClientAllowedResource(ctx context.Context, arg AddClientAllowedResourceParams) error
	AddClientRedirectURI(ctx context.Context, arg AddClientRedirectURIParams) error
	ApproveDeviceCode(ctx context.Context, arg ApproveDeviceCodeParams) error
	AttachAuthRequestSession(ctx context.Context, arg AttachAuthRequestSessionParams) error
	// tenantguard: global-ok (tenant_id pinned in params)
	ClearLoginFailures(ctx context.Context, arg ClearLoginFailuresParams) error
	ConfirmUserTOTP(ctx context.Context, arg ConfirmUserTOTPParams) error
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (*UserRecoveryCode, error)
	ConsumeWebAuthnChallenge(ctx context.Context, arg ConsumeWebAuthnChallengeParams) (*WebauthnChallenge, error)
	CountActiveRecoveryCodes(ctx context.Context, arg CountActiveRecoveryCodesParams) (int64, error)
	// tenantguard: global-ok (tenant_id pinned in params)
	CountRecentLoginFailures(ctx context.Context, arg CountRecentLoginFailuresParams) (int64, error)
	CreateAuthRequest(ctx context.Context, arg CreateAuthRequestParams) (*AuthRequest, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (*Client, error)
	CreateIdPConnector(ctx context.Context, arg CreateIdPConnectorParams) (*IdpConnector, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error)
	CreateTenant(ctx context.Context, arg CreateTenantParams) (*Tenant, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	DeleteClient(ctx context.Context, arg DeleteClientParams) error
	DeleteClientAllowedResource(ctx context.Context, arg DeleteClientAllowedResourceParams) error
	DeleteClientRedirectURI(ctx context.Context, arg DeleteClientRedirectURIParams) error
	// tenantguard: global-ok (background sweep across tenants; status-driven)
	DeleteExpiredPARRequests(ctx context.Context, expiresAt time.Time) error
	DeleteIdPConnector(ctx context.Context, arg DeleteIdPConnectorParams) error
	// tenantguard: global-ok (tenant_id pinned in params)
	DeleteLockout(ctx context.Context, arg DeleteLockoutParams) error
	DeleteRecoveryCodesForUser(ctx context.Context, arg DeleteRecoveryCodesForUserParams) error
	// tenantguard: global-ok (background sweep across all tenants; status-driven, not tenant-driven)
	DeleteRetiredJWKSKeys(ctx context.Context, retiredAt pgtype.Timestamptz) error
	DeleteTenant(ctx context.Context, id uuid.UUID) error
	DeleteUserTOTP(ctx context.Context, arg DeleteUserTOTPParams) error
	DeleteWebAuthnCredential(ctx context.Context, arg DeleteWebAuthnCredentialParams) error
	DenyDeviceCode(ctx context.Context, arg DenyDeviceCodeParams) error
	GetAccessTokenByHash(ctx context.Context, arg GetAccessTokenByHashParams) (*AccessToken, error)
	GetActiveJWKSKey(ctx context.Context, arg GetActiveJWKSKeyParams) (*JwksKey, error)
	// tenantguard: global-ok (tenant_id pinned in params)
	GetActiveLockout(ctx context.Context, arg GetActiveLockoutParams) (*AccountLockout, error)
	GetActiveUserConsent(ctx context.Context, arg GetActiveUserConsentParams) (*UserConsent, error)
	GetAuthRequest(ctx context.Context, arg GetAuthRequestParams) (*AuthRequest, error)
	GetAuthRequestByCodeHash(ctx context.Context, arg GetAuthRequestByCodeHashParams) (*AuthRequest, error)
	GetAuthRequestByFederationState(ctx context.Context, arg GetAuthRequestByFederationStateParams) (*AuthRequest, error)
	GetCIBAByAuthReqID(ctx context.Context, arg GetCIBAByAuthReqIDParams) (*CibaRequest, error)
	GetClientByClientID(ctx context.Context, arg GetClientByClientIDParams) (*Client, error)
	GetClientByID(ctx context.Context, arg GetClientByIDParams) (*Client, error)
	GetDeviceCodeByDeviceCode(ctx context.Context, arg GetDeviceCodeByDeviceCodeParams) (*DeviceCode, error)
	GetDeviceCodeByUserCode(ctx context.Context, arg GetDeviceCodeByUserCodeParams) (*DeviceCode, error)
	GetFederatedUser(ctx context.Context, arg GetFederatedUserParams) (*FederatedIdentity, error)
	GetIdPConnectorByID(ctx context.Context, arg GetIdPConnectorByIDParams) (*IdpConnector, error)
	GetIdPConnectorBySlug(ctx context.Context, arg GetIdPConnectorBySlugParams) (*IdpConnector, error)
	// tenantguard: global-ok (kid is a SHA-256 hash and globally unique by construction; verifiers may not know the tenant yet)
	GetJWKSKeyByKID(ctx context.Context, kid string) (*JwksKey, error)
	GetPARRequest(ctx context.Context, arg GetPARRequestParams) (*ParRequest, error)
	// tenantguard: global-ok (rate_buckets is not tenant-scoped)
	GetRateBucket(ctx context.Context, arg GetRateBucketParams) (*RateBucket, error)
	GetRefreshTokenByHash(ctx context.Context, arg GetRefreshTokenByHashParams) (*RefreshToken, error)
	// tenantguard: global-ok (lookup-by-name on global role catalog)
	GetRoleByName(ctx context.Context, name string) (*Role, error)
	GetSession(ctx context.Context, arg GetSessionParams) (*Session, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (*Tenant, error)
	GetTenantByIssuer(ctx context.Context, issuer string) (*Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (*Tenant, error)
	GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (*User, error)
	GetUserByID(ctx context.Context, arg GetUserByIDParams) (*User, error)
	GetUserCredentials(ctx context.Context, arg GetUserCredentialsParams) (*UserCredential, error)
	GetUserTOTP(ctx context.Context, arg GetUserTOTPParams) (*UserMfaTotp, error)
	GrantRole(ctx context.Context, arg GrantRoleParams) error
	// tenantguard: global-ok (background sweep across all tenants; deletes by deleted_at age)
	HardDeleteExpiredUsers(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error)
	InsertAccessToken(ctx context.Context, arg InsertAccessTokenParams) (*AccessToken, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (*AuditLog, error)
	InsertCIBARequest(ctx context.Context, arg InsertCIBARequestParams) (*CibaRequest, error)
	InsertDeviceCode(ctx context.Context, arg InsertDeviceCodeParams) (*DeviceCode, error)
	InsertJWKSKey(ctx context.Context, arg InsertJWKSKeyParams) (*JwksKey, error)
	InsertPARRequest(ctx context.Context, arg InsertPARRequestParams) (*ParRequest, error)
	InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (*RefreshToken, error)
	InsertWebAuthnChallenge(ctx context.Context, arg InsertWebAuthnChallengeParams) (*WebauthnChallenge, error)
	InsertWebAuthnCredential(ctx context.Context, arg InsertWebAuthnCredentialParams) (*UserWebauthnCredential, error)
	LinkFederatedIdentity(ctx context.Context, arg LinkFederatedIdentityParams) (*FederatedIdentity, error)
	ListActiveRecoveryCodes(ctx context.Context, arg ListActiveRecoveryCodesParams) ([]*UserRecoveryCode, error)
	ListAllJWKSKeys(ctx context.Context, tenantID pgtype.UUID) ([]*JwksKey, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]*AuditLog, error)
	ListClientAllowedResources(ctx context.Context, arg ListClientAllowedResourcesParams) ([]string, error)
	ListClientRedirectURIs(ctx context.Context, arg ListClientRedirectURIsParams) ([]string, error)
	ListClientsByTenant(ctx context.Context, arg ListClientsByTenantParams) ([]*Client, error)
	ListEnabledIdPConnectors(ctx context.Context, tenantID uuid.UUID) ([]*IdpConnector, error)
	ListFederatedIdentitiesForUser(ctx context.Context, arg ListFederatedIdentitiesForUserParams) ([]*ListFederatedIdentitiesForUserRow, error)
	ListPendingCIBAForUser(ctx context.Context, arg ListPendingCIBAForUserParams) ([]*CibaRequest, error)
	ListPublicJWKSKeys(ctx context.Context, tenantID pgtype.UUID) ([]*JwksKey, error)
	ListRefreshTokensInFamily(ctx context.Context, arg ListRefreshTokensInFamilyParams) ([]*RefreshToken, error)
	// tenantguard: global-ok (roles is the global role catalog, not tenant-scoped)
	ListRoles(ctx context.Context) ([]*Role, error)
	ListRolesForUser(ctx context.Context, arg ListRolesForUserParams) ([]*Role, error)
	ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]*Session, error)
	ListTenants(ctx context.Context, arg ListTenantsParams) ([]*Tenant, error)
	ListUserConsents(ctx context.Context, arg ListUserConsentsParams) ([]*UserConsent, error)
	ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]*User, error)
	ListUsersInRole(ctx context.Context, arg ListUsersInRoleParams) ([]*User, error)
	ListWebAuthnCredentialsForUser(ctx context.Context, arg ListWebAuthnCredentialsForUserParams) ([]*UserWebauthnCredential, error)
	MarkAuthRequestCodeConsumed(ctx context.Context, arg MarkAuthRequestCodeConsumedParams) error
	MarkAuthRequestConsentedAndCode(ctx context.Context, arg MarkAuthRequestConsentedAndCodeParams) error
	// tenantguard: global-ok (called inside Rotate's tx, key was just read by id with tenant filter applied)
	MarkJWKSKeyRotated(ctx context.Context, arg MarkJWKSKeyRotatedParams) error
	MarkPARRequestConsumed(ctx context.Context, arg MarkPARRequestConsumedParams) error
	MarkRefreshTokenConsumed(ctx context.Context, arg MarkRefreshTokenConsumedParams) error
	// tenantguard: global-ok (deliberate per-tenant insert, tenant_id pinned in params)
	RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error
	RedeemDeviceCode(ctx context.Context, arg RedeemDeviceCodeParams) error
	ReplaceClientAllowedResources(ctx context.Context, arg ReplaceClientAllowedResourcesParams) error
	ReplaceClientRedirectURIs(ctx context.Context, arg ReplaceClientRedirectURIsParams) error
	// tenantguard: global-ok (background sweep across all tenants; status-driven, not tenant-driven)
	RetireJWKSKeysOlderThan(ctx context.Context, arg RetireJWKSKeysOlderThanParams) error
	RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error
	// Used by refresh-token reuse detection: when a consumed RT is presented
	// again, the entire family's still-live access tokens are revoked too.
	// tenantguard: global-ok (filter is by token id and the surrounding tx already loaded the family scoped to a tenant)
	RevokeAllAccessTokensForFamily(ctx context.Context, dollar_1 []uuid.UUID) error
	RevokeAllSessionsForUser(ctx context.Context, arg RevokeAllSessionsForUserParams) error
	RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error
	RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error
	RevokeRole(ctx context.Context, arg RevokeRoleParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeUserConsent(ctx context.Context, arg RevokeUserConsentParams) error
	RotateClientSecret(ctx context.Context, arg RotateClientSecretParams) error
	SetAuthRequestFederation(ctx context.Context, arg SetAuthRequestFederationParams) error
	SetCIBAStatus(ctx context.Context, arg SetCIBAStatusParams) error
	SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error
	TouchCIBAPoll(ctx context.Context, arg TouchCIBAPollParams) error
	TouchDeviceCodePoll(ctx context.Context, arg TouchDeviceCodePollParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	TouchUserTOTP(ctx context.Context, arg TouchUserTOTPParams) error
	UnlinkFederatedIdentity(ctx context.Context, arg UnlinkFederatedIdentityParams) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) (*Client, error)
	UpdateTenant(ctx context.Context, arg UpdateTenantParams) (*Tenant, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error)
	UpdateWebAuthnSignCount(ctx context.Context, arg UpdateWebAuthnSignCountParams) error
	UpgradeSessionMFA(ctx context.Context, arg UpgradeSessionMFAParams) error
	// tenantguard: global-ok (tenant_id pinned in params)
	UpsertLockout(ctx context.Context, arg UpsertLockoutParams) error
	// tenantguard: global-ok (rate_buckets is not tenant-scoped; key is opaque)
	UpsertRateBucket(ctx context.Context, arg UpsertRateBucketParams) (*RateBucket, error)
	UpsertUserConsent(ctx context.Context, arg UpsertUserConsentParams) error
	UpsertUserCredentials(ctx context.Context, arg UpsertUserCredentialsParams) error
	UpsertUserTOTP(ctx context.Context, arg UpsertUserTOTPParams) error
}

var _ Querier = (*Queries)(nil)
