// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rbac.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getRoleByName = `-- name: GetRoleByName :one
SELECT id, name, description, permissions, created_at FROM roles WHERE name = $1
`

// tenantguard: global-ok (lookup-by-name on global role catalog)
func (q *Queries) GetRoleByName(ctx context.Context, name string) (*Role, error) {
	row := q.db.QueryRow(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Permissions,
		&i.CreatedAt,
	)
	return &i, err
}

const grantRole = `-- name: GrantRole :exec
INSERT INTO user_roles (tenant_id, user_id, role_id)
VALUES ($1, $2, $3)
ON CONFLICT (user_id, role_id, tenant_id) DO NOTHING
`

type GrantRoleParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
	RoleID   uuid.UUID `db:"role_id"`
}

func (q *Queries) GrantRole(ctx context.Context, arg GrantRoleParams) error {
	_, err := q.db.Exec(ctx, grantRole, arg.TenantID, arg.UserID, arg.RoleID)
	return err
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, description, permissions, created_at FROM roles
ORDER BY name ASC
`

// tenantguard: global-ok (roles is the global role catalog, not tenant-scoped)
func (q *Queries) ListRoles(ctx context.Context) ([]*Role, error) {
	rows, err := q.db.Query(ctx, listRoles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesForUser = `-- name: ListRolesForUser :many
SELECT r.id, r.name, r.description, r.permissions, r.created_at FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.tenant_id = $1 AND ur.user_id = $2
ORDER BY r.name ASC
`

type ListRolesForUserParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

func (q *Queries) ListRolesForUser(ctx context.Context, arg ListRolesForUserParams) ([]*Role, error) {
	rows, err := q.db.Query(ctx, listRolesForUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Role{}
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Permissions,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersInRole = `-- name: ListUsersInRole :many
SELECT u.id, u.tenant_id, u.email, u.email_verified, u.display_name, u.locale, u.zoneinfo, u.picture_url, u.enabled, u.created_at, u.updated_at, u.deleted_at FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r       ON r.id = ur.role_id
WHERE ur.tenant_id = $1 AND r.name = $2
ORDER BY u.email ASC
`

type ListUsersInRoleParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	Name     string    `db:"name"`
}

func (q *Queries) ListUsersInRole(ctx context.Context, arg ListUsersInRoleParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersInRole, arg.TenantID, arg.Name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.EmailVerified,
			&i.DisplayName,
			&i.Locale,
			&i.Zoneinfo,
			&i.PictureUrl,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRole = `-- name: RevokeRole :exec
DELETE FROM user_roles
WHERE tenant_id = $1 AND user_id = $2 AND role_id = $3
`

type RevokeRoleParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
	RoleID   uuid.UUID `db:"role_id"`
}

func (q *Queries) RevokeRole(ctx context.Context, arg RevokeRoleParams) error {
	_, err := q.db.Exec(ctx, revokeRole, arg.TenantID, arg.UserID, arg.RoleID)
	return err
}
