// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: security.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearLoginFailures = `-- name: ClearLoginFailures :exec
DELETE FROM login_failures
WHERE tenant_id = $1 AND email_hash = $2
`

type ClearLoginFailuresParams struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	EmailHash []byte    `db:"email_hash"`
}

// tenantguard: global-ok (tenant_id pinned in params)
func (q *Queries) ClearLoginFailures(ctx context.Context, arg ClearLoginFailuresParams) error {
	_, err := q.db.Exec(ctx, clearLoginFailures, arg.TenantID, arg.EmailHash)
	return err
}

const countRecentLoginFailures = `-- name: CountRecentLoginFailures :one
SELECT COUNT(*) FROM login_failures
WHERE tenant_id = $1
  AND email_hash = $2
  AND occurred_at > $3
`

type CountRecentLoginFailuresParams struct {
	TenantID   uuid.UUID `db:"tenant_id"`
	EmailHash  []byte    `db:"email_hash"`
	OccurredAt time.Time `db:"occurred_at"`
}

// tenantguard: global-ok (tenant_id pinned in params)
func (q *Queries) CountRecentLoginFailures(ctx context.Context, arg CountRecentLoginFailuresParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentLoginFailures, arg.TenantID, arg.EmailHash, arg.OccurredAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteLockout = `-- name: DeleteLockout :exec
DELETE FROM account_lockouts
WHERE tenant_id = $1 AND email_hash = $2
`

type DeleteLockoutParams struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	EmailHash []byte    `db:"email_hash"`
}

// tenantguard: global-ok (tenant_id pinned in params)
func (q *Queries) DeleteLockout(ctx context.Context, arg DeleteLockoutParams) error {
	_, err := q.db.Exec(ctx, deleteLockout, arg.TenantID, arg.EmailHash)
	return err
}

const getActiveLockout = `-- name: GetActiveLockout :one
SELECT tenant_id, email_hash, locked_at, unlock_at, reason FROM account_lockouts
WHERE tenant_id = $1
  AND email_hash = $2
  AND unlock_at > NOW()
`

type GetActiveLockoutParams struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	EmailHash []byte    `db:"email_hash"`
}

// tenantguard: global-ok (tenant_id pinned in params)
func (q *Queries) GetActiveLockout(ctx context.Context, arg GetActiveLockoutParams) (*AccountLockout, error) {
	row := q.db.QueryRow(ctx, getActiveLockout, arg.TenantID, arg.EmailHash)
	var i AccountLockout
	err := row.Scan(
		&i.TenantID,
		&i.EmailHash,
		&i.LockedAt,
		&i.UnlockAt,
		&i.Reason,
	)
	return &i, err
}

const getRateBucket = `-- name: GetRateBucket :one
SELECT endpoint, key, level, updated_at FROM rate_buckets WHERE endpoint = $1 AND key = $2
`

type GetRateBucketParams struct {
	Endpoint string `db:"endpoint"`
	Key      string `db:"key"`
}

// tenantguard: global-ok (rate_buckets is not tenant-scoped)
func (q *Queries) GetRateBucket(ctx context.Context, arg GetRateBucketParams) (*RateBucket, error) {
	row := q.db.QueryRow(ctx, getRateBucket, arg.Endpoint, arg.Key)
	var i RateBucket
	err := row.Scan(
		&i.Endpoint,
		&i.Key,
		&i.Level,
		&i.UpdatedAt,
	)
	return &i, err
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
INSERT INTO login_failures (tenant_id, email_hash, ip)
VALUES ($1, $2, $3)
`

type RecordLoginFailureParams struct {
	TenantID  uuid.UUID   `db:"tenant_id"`
	EmailHash []byte      `db:"email_hash"`
	Ip        pgtype.Text `db:"ip"`
}

// tenantguard: global-ok (deliberate per-tenant insert, tenant_id pinned in params)
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error {
	_, err := q.db.Exec(ctx, recordLoginFailure, arg.TenantID, arg.EmailHash, arg.Ip)
	return err
}

const upsertLockout = `-- name: UpsertLockout :exec
INSERT INTO account_lockouts (tenant_id, email_hash, unlock_at, reason)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, email_hash) DO UPDATE
SET unlock_at = EXCLUDED.unlock_at,
    reason    = EXCLUDED.reason,
    locked_at = NOW()
`

type UpsertLockoutParams struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	EmailHash []byte    `db:"email_hash"`
	UnlockAt  time.Time `db:"unlock_at"`
	Reason    string    `db:"reason"`
}

// tenantguard: global-ok (tenant_id pinned in params)
func (q *Queries) UpsertLockout(ctx context.Context, arg UpsertLockoutParams) error {
	_, err := q.db.Exec(ctx, upsertLockout,
		arg.TenantID,
		arg.EmailHash,
		arg.UnlockAt,
		arg.Reason,
	)
	return err
}

const upsertRateBucket = `-- name: UpsertRateBucket :one
INSERT INTO rate_buckets (endpoint, key, level)
VALUES ($1, $2, $3)
ON CONFLICT (endpoint, key) DO UPDATE
SET level      = EXCLUDED.level,
    updated_at = NOW()
RETURNING endpoint, key, level, updated_at
`

type UpsertRateBucketParams struct {
	Endpoint string  `db:"endpoint"`
	Key      string  `db:"key"`
	Level    float64 `db:"level"`
}

// tenantguard: global-ok (rate_buckets is not tenant-scoped; key is opaque)
func (q *Queries) UpsertRateBucket(ctx context.Context, arg UpsertRateBucketParams) (*RateBucket, error) {
	row := q.db.QueryRow(ctx, upsertRateBucket, arg.Endpoint, arg.Key, arg.Level)
	var i RateBucket
	err := row.Scan(
		&i.Endpoint,
		&i.Key,
		&i.Level,
		&i.UpdatedAt,
	)
	return &i, err
}
