// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
    tenant_id, user_id, csrf_secret, ip, user_agent,
    mfa_level, amr, auth_time, expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9
)
RETURNING id, tenant_id, user_id, csrf_secret, ip, user_agent, mfa_level, amr, auth_time, last_seen_at, expires_at, revoked_at
`

type CreateSessionParams struct {
	TenantID   uuid.UUID   `db:"tenant_id"`
	UserID     uuid.UUID   `db:"user_id"`
	CsrfSecret string      `db:"csrf_secret"`
	Ip         pgtype.Text `db:"ip"`
	UserAgent  pgtype.Text `db:"user_agent"`
	MfaLevel   string      `db:"mfa_level"`
	Amr        []string    `db:"amr"`
	AuthTime   time.Time   `db:"auth_time"`
	ExpiresAt  time.Time   `db:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.TenantID,
		arg.UserID,
		arg.CsrfSecret,
		arg.Ip,
		arg.UserAgent,
		arg.MfaLevel,
		arg.Amr,
		arg.AuthTime,
		arg.ExpiresAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CsrfSecret,
		&i.Ip,
		&i.UserAgent,
		&i.MfaLevel,
		&i.Amr,
		&i.AuthTime,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return &i, err
}

const getSession = `-- name: GetSession :one
SELECT id, tenant_id, user_id, csrf_secret, ip, user_agent, mfa_level, amr, auth_time, last_seen_at, expires_at, revoked_at FROM sessions
WHERE id = $1
  AND tenant_id = $2
  AND revoked_at IS NULL
  AND expires_at > NOW()
`

type GetSessionParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, getSession, arg.ID, arg.TenantID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.CsrfSecret,
		&i.Ip,
		&i.UserAgent,
		&i.MfaLevel,
		&i.Amr,
		&i.AuthTime,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return &i, err
}

const listSessionsByUser = `-- name: ListSessionsByUser :many
SELECT id, tenant_id, user_id, csrf_secret, ip, user_agent, mfa_level, amr, auth_time, last_seen_at, expires_at, revoked_at FROM sessions
WHERE tenant_id = $1
  AND user_id = $2
  AND revoked_at IS NULL
  AND expires_at > NOW()
ORDER BY last_seen_at DESC
`

type ListSessionsByUserParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

func (q *Queries) ListSessionsByUser(ctx context.Context, arg ListSessionsByUserParams) ([]*Session, error) {
	rows, err := q.db.Query(ctx, listSessionsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.CsrfSecret,
			&i.Ip,
			&i.UserAgent,
			&i.MfaLevel,
			&i.Amr,
			&i.AuthTime,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE tenant_id = $1
  AND user_id = $2
  AND revoked_at IS NULL
`

type RevokeAllSessionsForUserParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	UserID   uuid.UUID `db:"user_id"`
}

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, arg RevokeAllSessionsForUserParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsForUser, arg.TenantID, arg.UserID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type RevokeSessionParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.TenantID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type TouchSessionParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.TenantID)
	return err
}

const upgradeSessionMFA = `-- name: UpgradeSessionMFA :exec
UPDATE sessions
SET mfa_level   = $3,
    amr         = $4,
    last_seen_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type UpgradeSessionMFAParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
	MfaLevel string    `db:"mfa_level"`
	Amr      []string  `db:"amr"`
}

func (q *Queries) UpgradeSessionMFA(ctx context.Context, arg UpgradeSessionMFAParams) error {
	_, err := q.db.Exec(ctx, upgradeSessionMFA,
		arg.ID,
		arg.TenantID,
		arg.MfaLevel,
		arg.Amr,
	)
	return err
}
