// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenants.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (slug, display_name, issuer)
VALUES ($1, $2, $3)
RETURNING id, slug, display_name, issuer, enabled, created_at, updated_at
`

type CreateTenantParams struct {
	Slug        string `db:"slug"`
	DisplayName string `db:"display_name"`
	Issuer      string `db:"issuer"`
}

func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (*Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant, arg.Slug, arg.DisplayName, arg.Issuer)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteTenant = `-- name: DeleteTenant :exec
DELETE FROM tenants
WHERE id = $1
`

func (q *Queries) DeleteTenant(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTenant, id)
	return err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, display_name, issuer, enabled, created_at, updated_at FROM tenants
WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (*Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantByIssuer = `-- name: GetTenantByIssuer :one
SELECT id, slug, display_name, issuer, enabled, created_at, updated_at FROM tenants
WHERE issuer = $1
`

func (q *Queries) GetTenantByIssuer(ctx context.Context, issuer string) (*Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByIssuer, issuer)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, display_name, issuer, enabled, created_at, updated_at FROM tenants
WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (*Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, display_name, issuer, enabled, created_at, updated_at FROM tenants
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListTenantsParams struct {
	Limit  int32 `db:"limit"`
	Offset int32 `db:"offset"`
}

func (q *Queries) ListTenants(ctx context.Context, arg ListTenantsParams) ([]*Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Issuer,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenant = `-- name: UpdateTenant :one
UPDATE tenants
SET display_name = $2,
    issuer       = $3,
    enabled      = $4,
    updated_at   = NOW()
WHERE id = $1
RETURNING id, slug, display_name, issuer, enabled, created_at, updated_at
`

type UpdateTenantParams struct {
	ID          uuid.UUID `db:"id"`
	DisplayName string    `db:"display_name"`
	Issuer      string    `db:"issuer"`
	Enabled     bool      `db:"enabled"`
}

func (q *Queries) UpdateTenant(ctx context.Context, arg UpdateTenantParams) (*Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenant,
		arg.ID,
		arg.DisplayName,
		arg.Issuer,
		arg.Enabled,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Issuer,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
