// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAccessTokenByHash = `-- name: GetAccessTokenByHash :one
SELECT id, tenant_id, token_hash, client_id, user_id, scopes, audience, cnf_jkt, cnf_x5t_s256, session_id, issued_at, expires_at, revoked_at FROM access_tokens
WHERE tenant_id = $1
  AND token_hash = $2
  AND revoked_at IS NULL
`

type GetAccessTokenByHashParams struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	TokenHash string    `db:"token_hash"`
}

func (q *Queries) GetAccessTokenByHash(ctx context.Context, arg GetAccessTokenByHashParams) (*AccessToken, error) {
	row := q.db.QueryRow(ctx, getAccessTokenByHash, arg.TenantID, arg.TokenHash)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.Audience,
		&i.CnfJkt,
		&i.CnfX5tS256,
		&i.SessionID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return &i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, tenant_id, token_hash, client_id, user_id, scopes, family_id, parent_id, cnf_jkt, cnf_x5t_s256, issued_at, expires_at, consumed_at, revoked_at FROM refresh_tokens
WHERE tenant_id = $1
  AND token_hash = $2
FOR UPDATE
`

type GetRefreshTokenByHashParams struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	TokenHash string    `db:"token_hash"`
}

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, arg GetRefreshTokenByHashParams) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, arg.TenantID, arg.TokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.FamilyID,
		&i.ParentID,
		&i.CnfJkt,
		&i.CnfX5tS256,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const insertAccessToken = `-- name: InsertAccessToken :one
INSERT INTO access_tokens (
    tenant_id, token_hash, client_id, user_id, scopes, audience,
    cnf_jkt, cnf_x5t_s256, session_id, issued_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, token_hash, client_id, user_id, scopes, audience, cnf_jkt, cnf_x5t_s256, session_id, issued_at, expires_at, revoked_at
`

type InsertAccessTokenParams struct {
	TenantID   uuid.UUID   `db:"tenant_id"`
	TokenHash  string      `db:"token_hash"`
	ClientID   uuid.UUID   `db:"client_id"`
	UserID     pgtype.UUID `db:"user_id"`
	Scopes     []string    `db:"scopes"`
	Audience   []string    `db:"audience"`
	CnfJkt     pgtype.Text `db:"cnf_jkt"`
	CnfX5tS256 pgtype.Text `db:"cnf_x5t_s256"`
	SessionID  pgtype.UUID `db:"session_id"`
	IssuedAt   time.Time   `db:"issued_at"`
	ExpiresAt  time.Time   `db:"expires_at"`
}

func (q *Queries) InsertAccessToken(ctx context.Context, arg InsertAccessTokenParams) (*AccessToken, error) {
	row := q.db.QueryRow(ctx, insertAccessToken,
		arg.TenantID,
		arg.TokenHash,
		arg.ClientID,
		arg.UserID,
		arg.Scopes,
		arg.Audience,
		arg.CnfJkt,
		arg.CnfX5tS256,
		arg.SessionID,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i AccessToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.Audience,
		&i.CnfJkt,
		&i.CnfX5tS256,
		&i.SessionID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return &i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (
    tenant_id, token_hash, client_id, user_id, scopes,
    family_id, parent_id, cnf_jkt, cnf_x5t_s256, issued_at, expires_at
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
)
RETURNING id, tenant_id, token_hash, client_id, user_id, scopes, family_id, parent_id, cnf_jkt, cnf_x5t_s256, issued_at, expires_at, consumed_at, revoked_at
`

type InsertRefreshTokenParams struct {
	TenantID   uuid.UUID   `db:"tenant_id"`
	TokenHash  string      `db:"token_hash"`
	ClientID   uuid.UUID   `db:"client_id"`
	UserID     uuid.UUID   `db:"user_id"`
	Scopes     []string    `db:"scopes"`
	FamilyID   uuid.UUID   `db:"family_id"`
	ParentID   pgtype.UUID `db:"parent_id"`
	CnfJkt     pgtype.Text `db:"cnf_jkt"`
	CnfX5tS256 pgtype.Text `db:"cnf_x5t_s256"`
	IssuedAt   time.Time   `db:"issued_at"`
	ExpiresAt  time.Time   `db:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken,
		arg.TenantID,
		arg.TokenHash,
		arg.ClientID,
		arg.UserID,
		arg.Scopes,
		arg.FamilyID,
		arg.ParentID,
		arg.CnfJkt,
		arg.CnfX5tS256,
		arg.IssuedAt,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.TokenHash,
		&i.ClientID,
		&i.UserID,
		&i.Scopes,
		&i.FamilyID,
		&i.ParentID,
		&i.CnfJkt,
		&i.CnfX5tS256,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.RevokedAt,
	)
	return &i, err
}

const listRefreshTokensInFamily = `-- name: ListRefreshTokensInFamily :many
SELECT id, tenant_id, token_hash, client_id, user_id, scopes, family_id, parent_id, cnf_jkt, cnf_x5t_s256, issued_at, expires_at, consumed_at, revoked_at FROM refresh_tokens
WHERE tenant_id = $1
  AND family_id = $2
ORDER BY issued_at ASC
`

type ListRefreshTokensInFamilyParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	FamilyID uuid.UUID `db:"family_id"`
}

func (q *Queries) ListRefreshTokensInFamily(ctx context.Context, arg ListRefreshTokensInFamilyParams) ([]*RefreshToken, error) {
	rows, err := q.db.Query(ctx, listRefreshTokensInFamily, arg.TenantID, arg.FamilyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*RefreshToken{}
	for rows.Next() {
		var i RefreshToken
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.TokenHash,
			&i.ClientID,
			&i.UserID,
			&i.Scopes,
			&i.FamilyID,
			&i.ParentID,
			&i.CnfJkt,
			&i.CnfX5tS256,
			&i.IssuedAt,
			&i.ExpiresAt,
			&i.ConsumedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRefreshTokenConsumed = `-- name: MarkRefreshTokenConsumed :exec
UPDATE refresh_tokens
SET consumed_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type MarkRefreshTokenConsumedParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) MarkRefreshTokenConsumed(ctx context.Context, arg MarkRefreshTokenConsumedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenConsumed, arg.ID, arg.TenantID)
	return err
}

const revokeAccessToken = `-- name: RevokeAccessToken :exec
UPDATE access_tokens
SET revoked_at = NOW()
WHERE tenant_id = $1
  AND token_hash = $2
  AND revoked_at IS NULL
`

type RevokeAccessTokenParams struct {
	TenantID  uuid.UUID `db:"tenant_id"`
	TokenHash string    `db:"token_hash"`
}

func (q *Queries) RevokeAccessToken(ctx context.Context, arg RevokeAccessTokenParams) error {
	_, err := q.db.Exec(ctx, revokeAccessToken, arg.TenantID, arg.TokenHash)
	return err
}

const revokeAllAccessTokensForFamily = `-- name: RevokeAllAccessTokensForFamily :exec
UPDATE access_tokens
SET revoked_at = NOW()
WHERE id = ANY($1::uuid[])
  AND revoked_at IS NULL
`

// Used by refresh-token reuse detection: when a consumed RT is presented
// again, the entire family's still-live access tokens are revoked too.
// tenantguard: global-ok (filter is by token id and the surrounding tx already loaded the family scoped to a tenant)
func (q *Queries) RevokeAllAccessTokensForFamily(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllAccessTokensForFamily, dollar_1)
	return err
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE tenant_id = $1
  AND family_id = $2
  AND revoked_at IS NULL
`

type RevokeRefreshFamilyParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	FamilyID uuid.UUID `db:"family_id"`
}

func (q *Queries) RevokeRefreshFamily(ctx context.Context, arg RevokeRefreshFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, arg.TenantID, arg.FamilyID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens
SET revoked_at = NOW()
WHERE id = $1
  AND tenant_id = $2
  AND revoked_at IS NULL
`

type RevokeRefreshTokenParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) RevokeRefreshToken(ctx context.Context, arg RevokeRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, arg.ID, arg.TenantID)
	return err
}
