// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (tenant_id, email, email_verified, display_name, locale, zoneinfo)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, email, email_verified, display_name, locale, zoneinfo, picture_url, enabled, created_at, updated_at, deleted_at
`

type CreateUserParams struct {
	TenantID      uuid.UUID   `db:"tenant_id"`
	Email         string      `db:"email"`
	EmailVerified bool        `db:"email_verified"`
	DisplayName   pgtype.Text `db:"display_name"`
	Locale        pgtype.Text `db:"locale"`
	Zoneinfo      pgtype.Text `db:"zoneinfo"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.TenantID,
		arg.Email,
		arg.EmailVerified,
		arg.DisplayName,
		arg.Locale,
		arg.Zoneinfo,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Locale,
		&i.Zoneinfo,
		&i.PictureUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, tenant_id, email, email_verified, display_name, locale, zoneinfo, picture_url, enabled, created_at, updated_at, deleted_at FROM users
WHERE tenant_id = $1
  AND lower(email) = lower($2)
  AND deleted_at IS NULL
`

type GetUserByEmailParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	Lower    string    `db:"lower"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, arg GetUserByEmailParams) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, arg.TenantID, arg.Lower)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Locale,
		&i.Zoneinfo,
		&i.PictureUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tenant_id, email, email_verified, display_name, locale, zoneinfo, picture_url, enabled, created_at, updated_at, deleted_at FROM users
WHERE id = $1
  AND tenant_id = $2
  AND deleted_at IS NULL
`

type GetUserByIDParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetUserByID(ctx context.Context, arg GetUserByIDParams) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, arg.ID, arg.TenantID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Locale,
		&i.Zoneinfo,
		&i.PictureUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const getUserCredentials = `-- name: GetUserCredentials :one
SELECT user_id, tenant_id, password_hash, algorithm, must_change, updated_at FROM user_credentials
WHERE user_id = $1
  AND tenant_id = $2
`

type GetUserCredentialsParams struct {
	UserID   uuid.UUID `db:"user_id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) GetUserCredentials(ctx context.Context, arg GetUserCredentialsParams) (*UserCredential, error) {
	row := q.db.QueryRow(ctx, getUserCredentials, arg.UserID, arg.TenantID)
	var i UserCredential
	err := row.Scan(
		&i.UserID,
		&i.TenantID,
		&i.PasswordHash,
		&i.Algorithm,
		&i.MustChange,
		&i.UpdatedAt,
	)
	return &i, err
}

const listUsersByTenant = `-- name: ListUsersByTenant :many
SELECT id, tenant_id, email, email_verified, display_name, locale, zoneinfo, picture_url, enabled, created_at, updated_at, deleted_at FROM users
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id"`
	Limit    int32     `db:"limit"`
	Offset   int32     `db:"offset"`
}

func (q *Queries) ListUsersByTenant(ctx context.Context, arg ListUsersByTenantParams) ([]*User, error) {
	rows, err := q.db.Query(ctx, listUsersByTenant, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.EmailVerified,
			&i.DisplayName,
			&i.Locale,
			&i.Zoneinfo,
			&i.PictureUrl,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET deleted_at = NOW(),
    enabled    = FALSE,
    updated_at = NOW()
WHERE id = $1
  AND tenant_id = $2
`

type SoftDeleteUserParams struct {
	ID       uuid.UUID `db:"id"`
	TenantID uuid.UUID `db:"tenant_id"`
}

func (q *Queries) SoftDeleteUser(ctx context.Context, arg SoftDeleteUserParams) error {
	_, err := q.db.Exec(ctx, softDeleteUser, arg.ID, arg.TenantID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET email          = $3,
    email_verified = $4,
    display_name   = $5,
    locale         = $6,
    zoneinfo       = $7,
    picture_url    = $8,
    enabled        = $9,
    updated_at     = NOW()
WHERE id = $1
  AND tenant_id = $2
RETURNING id, tenant_id, email, email_verified, display_name, locale, zoneinfo, picture_url, enabled, created_at, updated_at, deleted_at
`

type UpdateUserParams struct {
	ID            uuid.UUID   `db:"id"`
	TenantID      uuid.UUID   `db:"tenant_id"`
	Email         string      `db:"email"`
	EmailVerified bool        `db:"email_verified"`
	DisplayName   pgtype.Text `db:"display_name"`
	Locale        pgtype.Text `db:"locale"`
	Zoneinfo      pgtype.Text `db:"zoneinfo"`
	PictureUrl    pgtype.Text `db:"picture_url"`
	Enabled       bool        `db:"enabled"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (*User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.TenantID,
		arg.Email,
		arg.EmailVerified,
		arg.DisplayName,
		arg.Locale,
		arg.Zoneinfo,
		arg.PictureUrl,
		arg.Enabled,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Locale,
		&i.Zoneinfo,
		&i.PictureUrl,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return &i, err
}

const upsertUserCredentials = `-- name: UpsertUserCredentials :exec
INSERT INTO user_credentials (user_id, tenant_id, password_hash, algorithm, must_change)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
SET password_hash = EXCLUDED.password_hash,
    algorithm     = EXCLUDED.algorithm,
    must_change   = EXCLUDED.must_change,
    updated_at    = NOW()
`

type UpsertUserCredentialsParams struct {
	UserID       uuid.UUID `db:"user_id"`
	TenantID     uuid.UUID `db:"tenant_id"`
	PasswordHash string    `db:"password_hash"`
	Algorithm    string    `db:"algorithm"`
	MustChange   bool      `db:"must_change"`
}

func (q *Queries) UpsertUserCredentials(ctx context.Context, arg UpsertUserCredentialsParams) error {
	_, err := q.db.Exec(ctx, upsertUserCredentials,
		arg.UserID,
		arg.TenantID,
		arg.PasswordHash,
		arg.Algorithm,
		arg.MustChange,
	)
	return err
}
