// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users_purge.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const hardDeleteExpiredUsers = `-- name: HardDeleteExpiredUsers :execrows
DELETE FROM users
WHERE deleted_at IS NOT NULL
  AND deleted_at < $1
`

// tenantguard: global-ok (background sweep across all tenants; deletes by deleted_at age)
func (q *Queries) HardDeleteExpiredUsers(ctx context.Context, deletedAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, hardDeleteExpiredUsers, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
